= Angular
:doc-root: https://notes.jdata.pl
:toc: left
:toclevels: 4
:tabsize: 4
:docinfo1:

== Introduction

=== Install angular globally

[source,bash]
$ npm install -g @angular/cli@latest

=== Updating npm and Angular CLI

[source,bash]
$ sudo npm install -g npm
$ sudo npm uninstall -g angular-cli @angular/cli
$ npm cache clean
$ sudo npm install -g @angular/cli

=== Create project

[source,bash]
----
$ ng new my-app
$ cd my-app
$ ng serve --open
----

==== Configure bootstrap within a project

[source,bash]
$ npm install --save bootstrap@3

then go to angular.json and add `node_modules/bootstrap3/dist/css/bootstrap.min.css` to styles.

==== Generate new component

[source,bash]
$ ng generate component servers
$ ng g c servers //same as ng generate component

==== Creating selector an attribute

|===
|File|Code

|*.component.ts     |selector: '[app-servers]'
|*.html             |<div app-servers></div>
|===

==== Creating selector a class:

|===
|File|Code

|*.component.ts     |selector: '[.app-servers]'
|*.html             |<div class="app-servers"></div>
|===


[[binding]]
== Binding

Databinding:

* string interpolation - `{{ data }}`
* property binding - `[property]="data"`

.Event binding:

 (event)="expression"

[source]
<input type="text"
       class="form-control"
       (input)="onUgdateServenName($event)">

.Two way binding:

[source]
<input type="text"
       class="form-control"
       [(ngModel)]="serverName">

For Two-Way-Binding to work, you need to enable the ngModel directive.
This is done by adding the `FormsModule` to the `imports[]` array in the `AppModule`.

== Directives

[source]
<p *ngIf="serverCreated">Server was created, server name is {{serverName}}</p>

.if-else:

[source]
----
<p *ngIf="serverCreated; else noServer">
    Server was created, name {{serverName}}
</p>

<ng-template #noServer>
    <p>No server was created</p>
</ng-template>
----

.Directive types:

* structural directives
* attribute directives - change only the element they were placed on

.Attribute directive:

[source]
----
<p [ngStyle]="{backgroundColor: getColor()}"
   [ngClass]="{online: serverStatus == 'online'}">
        Server with ID {{serverId}} is {{getServerStatus()}}
</p>
----

.for loop

[source]
<app-server *ngFor="let _server_ of servers"></app-server>

[source]
----
<p *ngFor="let item of operations; let i = index"
   [ngClass]="{oldItem: i >= 4}"
   [ngStyle]="{
       backgroundColor: _i_ < 4 ? 'white' : 'blue'*
   }">{{item}}</p>
----

.Generate component, no test class
[source,bash]
$ ng g c recipes --spec false

.External properties:

`@Input` - property decorator

[source]
----
<app-server-element *ngFor="let serverElement of serverElements"
                    [element]="serverElement">
</app-server-element>
----

.Events:

Declaration:

[source]
@Output() serverCreated =
    new EventEmitter<{serverName: string, serverContent: string}>();

Usage:

[source]
<app-cockpit (serverCreated)="onServerAdded($event)">

=== View encapsulation

[source,typescript]
@Component({
    ...
    styleUrls: ['./server-element.compontent.css'],
    encapsulation: ViewEncapsulation.None
)

`encapsulation: ViewEncapsulation.None` doesn't use now view encapsulation.

`ViewEncapsulation.Native` uses shadow-DOM technology (not supported by older browsers).


=== Using local references:

[source]
----
<input type="text" class="form-control" #serverContentInput>
<button class="btn btn-primary"
        (click)="onAddServer(serverNameInput)">
    Add Server
</button>
----

Local references can be referred only in html code.

[source]
----
onAddServer(nameInput: HTMLInputElement) {
    console.log(nameInput.value);
}
----

.To reference DOM element:

[source]
@ViewChild('serverContentInput') serverContentInput: ElementRef;

Accessible after view init:

[source]
console.log(this.serverContentInput.nativeElement.value);

Accessible after content init:

[source]
@ContentChild('contentParagraph') paragraph: ElementRef;

.Projecting content into component:

[source]
<ng-content>

== Debugging

`Augury` tool to better understand app structure.

== Lifecycle hooks

[cols=""]
|===
|Name                   |Description

|ngOnChanges            |whenever @Input properties changes
|ngOnInit               |
|ngDoCheck              |Invoked when the change detector of the given component is invoked.
                         It allows us to implement our own change detection algorithm for the given component.
|ngAfterContextInit     |after content (ng-content) has been projected into view
|ngAfterContentChecked  |called every time the projected content has been checked
|ngAfterViewInit        |after the component’s view has been initialized
|ngAfterViewChecked     |
|ngOnDestroy            |
|===

Interfaces:

* OnInit,
* OnChanges,
* DoCheck
* AfterContentInit
* AfterContentChecked
* AfterViewInit
* AfterViewChecked
* OnDestroy

== Directives

* *attribute directives* - sit on elementsSo whS, only affect that attribute sit on
* *structural attributes* - change the structure of the DOM

[source,typescript]
----
@Directive({
    selector: '[appBasicHighlight]'
})
export class BasicHighlightDirective implements OnInit {
    constructor(private elementRef: ElementRef) {
    }

    ngOnInit(): void {
        this.elementRef.nativeElement.style.backgroundColor = 'green';
    }
}
----

Add to declarations in app.module.ts

[source,html]
<p appBasicHighlight>Style me with basic directive!</p>

To add new directive from command line:

[source,bash]
$ ng g d better-highlight

[source,typscript]
----
@Directive({
    selector: '[appBetterHighlight]'
})
export class BetterHighlightDirective implements OnInit {
    constructor(private elementRef: ElementRef, private renderer: Renderer2) {
    }

    ngOnInit(): void {
        this.renderer.setStyle(this.elementRef.nativeElement, 'background-color', 'blue');
    }
}
----

[source,typscript]
----
@Directive({selector: '[appBetterHighlight]'})
export class BetterHighlightDirective implements OnInit {

    @Input() defaultColor = 'transparent';

    @Input('appBetterHighlight') highlightColor = 'blue';

    @HostBinding('style.backgroundColor') backgorundColor: string = this.defaultColor;

    constructor(private elementRef: ElementRef, private renderer: Renderer2) {
    }

    ngOnInit(): void {
        this.backgorundColor = this.defaultColor;
    }

    @HostListener('mouseenter') mouseOver(eventData: Event) {
        this.backgorundColor = this.highlightColor;
    }

    @HostListener('mouseleave') mouseLeave(eventData: Event) {
        this.backgorundColor = this.defaultColor;
    }
}
----

=== ng-template

A code:

[source,typscript]
<p *ngIf="contition">Text</p>

gets transformed by Angular to:

[source,typscript]
<ng-template [ngIf]="condition">
    <p>text</p>
</ng-template>

=== Toggling style

[source,typscript]
----
@Directive({
    selector: '[appDropdown]'
})
export class DropdownDirective {

    @HostBinding('class.open') isOpen;

    @HostListener('click') onClick() {
        this.isOpen = !this.isOpen;
    }
}
----

=== Structural directive sample

[source,typscript]
----
@Directive({
  selector: '[appUnless]'
})
export class UnlessDirective {

  @Input('appUnless') set unless(condition: boolean) {
    if (condition) {
      this.viewContainerRef.clear();
    } else {
      this.viewContainerRef.createEmbeddedView(this.templateRef);
    }
  }

  constructor(private templateRef: TemplateRef<any>, private viewContainerRef: ViewContainerRef) {
  }

}
----

==== ng-switch

[source]
<div [ngSwitch]="value">
  <p *ngSwitchCase="5">Value is 5</p>
  <p *ngSwitchCase="10">Value is 10</p>
  <p *ngSwitchCase="15">Value is 15</p>
  <p *ngSwitchDefault="">Value is other</p>
</div>

== Routes

[source,typscript]
----
const appRoutes: Routes = [
    {path: '', component: HomeComponent},
    {path: 'users', component: UsersComponent},
    {path: 'servers', component: ServersComponent}
];
----

Import RouterModule in app.module.ts:

[source,typscript]
RouterModule.forRoot(appRoutes)

[source]
----
<router-outlet></router-outlet>

<a routerLink="/servers">
<a [routerLink]="['/users']">

<li role="presentation"
    routerLinkActive="active"
    [routerLinkActiveOptions]="{exact: true}">
    <a routerLink="/">Home</a>
</li>

<li role="presentation" routerLinkActive="active">
    <a routerLink="/servers">Servers</a>
</li>
----

.Routing programatically
[source,typscript]
----
constructor(private router: Router) {
}

this.router.navigate(['/servers']);
----

[[relative-routes]]
=== Relative routes

[source,typscript]
----
constructor(private router: Router,
            private route: ActivatedRoute) {
}

this.router.navigate(['servers'], {relativeTo: this.route});
----

.Parameterized routes

[source,typscript]
{path: 'users/:id', component: UserComponent}

.Updating values in the component by observable

[source,typscript]
----
export class UserComponent implements OnInit {
    user: { id: number, name: string };

    constructor(private route: ActivatedRoute) {
    }

    ngOnInit(): void {
        this.user = {
            id: this.route.snapshot.params['id'],
            name: this.route.snapshot.params['name']
        };

        this.route.params.subscribe(
            (params: Params) => {
                this.user.id = params['id'];
                this.user.name = params['name'];
            }
        );
    }
}
----

.Removing the subscription explicitly
[source]
----
implements OnDestroy

aSubscription: Subscription

ngOnInit() {
    this.aSubscription = this.route.params.subscribe(...);
}

ngOnDestroy() {
    this.aSubscription.unsubscribe();
}
----

This is not necessary for angular objects, but it is necessary for


== Links again

[source]
----
<a
    [routerLink]="['/servers', 5, 'edit']"
    [queryParams]="{allowEdit: '1'}"
    fragment="loading"
    href="#"
    class="list-group-item"
    *ngFor="let _server_ of servers">
        {{ server.name }}
</a>
----

[source,typscript]
----
this.router.navigate(
    ['/servers', id, 'edit'],
    {
        queryParams: {allowEdit: '1'},
        fragment: 'loading'
    }
);
----

.Redirecting not found:

[source,typscript]
----
{path: 'not-found', component: PageNotFoundComponent},
{path: '**', redirectTo: 'not-found'}
----

.Full path match:

[source,typscript]
{path: '', component: HomeComponent, pathMatch: 'full'}

=== Routing in separate module:

[source,typscript]
----
@NgModule({
    imports: [
        RouterModule.forRoot(appRoutes)
    ],
    exports: [
        RouterModule
    ]
})

export class AppRoutingModule {
}
----

=== Activating children

.In AuthGuard class:
[source]
... implements CanActivateChild

.In routes:
[source]
canActivateChild: [AuthGuard]

=== Child routes

[source,typescript]
  {
    path: 'servers',
    component: ServersComponent,
    children: [
      {path: ':id', component: ServerComponent, resolve: {server: ServerResolver}},
      {
        path: ':id/edit',
        component: EditServerComponent,
        canDeactivate: [CanDeactivateGuard]
      }
    ]
  }

== Guarding routes

[source,typscript]
----
@Injectable()
export class AuthGuard implements CanActivate {
    constructor(private authService: AuthService,
                private router: Router) {
    }

    canActivate(route: ActivatedRouteSnapshot,
                state: RouterStateSnapshot): Observable<boolean> | Promise<boolean> | boolean {
        return this.authService.isAuthenticated()
            .then(authenticated => {
                if (authenticated) {
                    return true;
                } else {
                    this.router.navigate(['/']);
                }
            });
    }
}
----

app.module.ts:


[source]
----
{
    path: 'servers',
    canActivate: [AuthGuard],
    component: ServersComponent,
}
----

== Routing data

In routing:

[source]
{path: 'not-found', component: ErrorPageComponent, data: {message: 'Page not found!'}}

usage:

[source,typscript]
this.errorMessage = this.route.snapshot.data['message'];

== Resolvers

[source,typscript]
----
@Injectable()
export class ServerResolver implements Resolve<Server> {
    constructor(private serverService: ServersService) {
    }

    resolve(route: ActivatedRouteSnapshot,
            state: RouterStateSnapshot): Observable<Server> | Promise<Server> | Server {
        return this.serverService.getServer(+route.params['id']);
    }
}
----

In routing:

 {path: ':id', component: ServerComponent, resolve: {server: ServerResolver}}

In component:

 this.route.data.subscribe()


Using # in paths:

[source]
RouterModule.forRoot(appRoutes, {useHash: true})

== Observables

`.subscribe()` method has three params:

* next
* error
* complete

[source,typscript]
----
import 'rxjs/Rx';

const myNumbers = Observable.interval(1000);

myNumbers.subscribe(
    (number: number) => console.log(number)
);
----

[source,typscript]
----
const myObservable = Observable.create((observer: Observer<string>) => {
    setTimeout(() => observer.next('first package'), 2000);
    setTimeout(() => observer.next('second package'), 4000);
    setTimeout(() => observer.error('this does not work'), 5000);
});

myObservable.subscribe(
    (data: string) => console.log(data),
    (error: string) => console.log(error),
    () => console.log('completed')
);
----

Always make sure to unsubscribe:

... implements *OnDestroy*

 mySubscription: Subscription
 mySubscription = observable.subscribe(...);
 mySubscription.unsubscribe();

.Rx.js website:
http://reactivex.io/

=== Subjects

 userActivated = new Subject();

 userActivated.next(3);

== Forms

Two approaches:

* template-driven - Angular infers the Form Object from the DOM
* reactive - from is created programmatically and synchronized with the DOM

[source]
<form (ngSubmit)="onSubmit(f)" #f="ngForm">

[source,typescript]
----
onSubmit(form: NgForm) {
    console.log(form);
    console.log(form.value);
}

@ViewChild('f') signupForm: NgForm;
----

.`required` directive:

[source]
<input type="text"
    id="username"
    name="username"
    class="form-control"
    ngModel
    required>

.`email` directive

[source]
----
<div class="form-group">
<label for="email">Mail</label>
<input type="email"
    id="email"
    class="form-control"
    ngModel
    name="email"
    required
    email
    #email="ngModel">
<span class="help-block"
      *ngIf="email.touched && !email.valid">
    Please enter a valid email!
</span>

@ViewChild('email') emailModel: NgModel;
----

https://angular.io/api/forms/Validators

.Disabling button when form is not valid
[source]
<button class="btn btn-primary"
        type="submit"
        [disabled]="!signupForm.valid"

.Setting default values with ngModel property binding
[source]
----
defaultQuestion = 'pet';

<select id="secret"
      name="secret"
      class="form-control"
      required
      [ngModel]="defaultQuestion">
    <option value="pet">Your first Pet?</option>
    <option value="teacher">Your first teacher?</option>
</select>
----

.Grouping content
[source]
----
<div id="user-data"
     ngModelGroup="userData"
     #userData="ngModelGroup">
    ...
</div>

<p *ngIf="userData.touched && !userData.valid">
    User data is invalid
</p>
----

.Radio buttons
[source]
----
genders = ['male', 'female'];

<div class="radio" *ngFor="let gender of genders">
    <label>
        <input type="radio"
               name="gender"
               ngModel
               [value]="gender"
               required>
        {{gender}}
    </label>
</div>
----

.Replacing values in all form fields

[source,typescript]
this.signupForm.setValue({
    userData: {
        username: suggestedName,
        email: 'test@example.com'
    },
    secret: 'pet',
    questionAnswer: '',
    gender: 'male'
});

.Replacing value in single field

[source,typescript]
this.signupForm.form.patchValue({
    userData: {
        username: suggestedName
    }
});

.Using form data

[source]
----
@ViewChild('f') form: NgForm;

user = {
    username: '',
    email: '',
    secretQuestion: '',
    answer: '',
    gender: ''
};

onSubmit() {
    this.user.username = this.form.value.userData.username;
    this.user.email = this.form.value.userData.email;
    this.user.secretQuestion = this.form.value.secret;
    this.user.answer = this.form.value.questionAnswer;
    this.user.gender = this.form.value.gender;
}
----

.Resetting form

[source]
this.form.reset();

== Programmatic forms

Import ReactiveFormsModule in app.module.ts imports section.

[source]
----
signupForm: FormGroup;

ngOnInit(): void {
  this.signupForm = new FormGroup({
    'username': new FormControl(null),
    'email': new FormControl(null),
    'gender': new FormControl('male')
  });
}

<form [formGroup]="signupForm">
  ...
  <input ...
     formControlName="username"
     ...

----

.Adding validators

[source]
new FormControl(null, Validators.required)

[source]
new FormControl(null, [Validators.required, Validators.email])

.Error messages

[source]
<span *ngIf="signupForm.get('username').touched && !signupForm.get('username').valid"
      class="help-block">
  Please enter a valid username!
</span>

.Grouping controls

[source,typescript]
----
signupForm: FormGroup;

this.signupForm = new FormGroup({
    'userData': new FormGroup({
        'username': new FormControl(null,
            [Validators.required, this.forbiddenNames.bind(this)]),
        'email': new FormControl(null,
            [Validators.required, Validators.email], this.forbiddenEmails)
    }),
    'gender': new FormControl('male'),
    'hobbies': new FormArray([])
});

<div formGroupName="userData">
    <input type="text"
           formControlName='username'
           ...>
    <span *ngIf="signupForm.get('userData.username').touched
                 && !signupForm.get('userData.username').valid"
          class="help-block">
        Please enter a valid username!
    </span>

<div>
----

.Arrays of controls

[source]
----
this.signupForm = new FormGroup({
    'hobbies': new FormArray([])
});

onAddHobby() {
    const control = new FormControl(null, Validators.required);
    (<FormArray>this.signupForm.get('hobbies')).push(control);
}

<div formArrayName="hobbies">
    <div class="form-group"
         *ngFor="let hobbyControl of signupForm.get('hobbies').controls; let i = index">
        <input type="text" class="form-control" [formControlName]="i">
    </div>
</div>
----

.Adding own validators

[source]
----
forbiddenUsernames = ['Chris', 'Anna'];

forbiddenNames(control: FormControl): { [s: string]: boolean } {
    if (this.forbiddenUsernames.indexOf(control.value) >= 0) {
        return {'nameIsForbidden': true};
    }
    return null;
}

this.signupForm = new FormGroup({
    'username': new FormControl('Jacek', [Validators.required, this.forbiddenNames.bind(this)])
});

<span *ngIf="signupForm.get('userData.username').touched
&& !signupForm.get('userData.username').valid"
      class="help-block">
  <span *ngIf="signupForm.get('userData.username')
  && signupForm.get('userData.username').errors['nameIsForbidden']">
    Name is forbidden!
  </span>
  <span *ngIf="signupForm.get('userData.username').errors['required']">
   This field is required!
  </span>
</span>
----

Asynchronous validators:

[source]
----
forbiddenEmails(control: FormControl): Promise<any> | Observable<any> {
    return new Promise<any>(((resolve) => {
        setTimeout(() => {
            if (control.value === 'test@t') {
                resolve({'emailIsForbidden': true});
            } else {
                resolve(*null*);
            }
        }, 1500);
    }));
}
----

Monitoring changes:

[source]
this.signupForm.valueChanges.subscribe(value => {
  console.log(value);
});
this.signupForm.statusChanges.subscribe(value => {
  console.log(value);
});


Two observables:

* FormGroup.statusChanges
* FormGroup.valueChanges

Pattern validator:
[source]
<input
    type="number"
    required
    [pattern]="'\\d+'">

== Pipes

.Example:
 {{username | uppercase}}

Pipes:

* uppercase
* date
* async - for promises

=== Pipe parameters

 {{ aDate | date:’fullDate’}}

=== Combining pipes

 {{ aDate | date:’fullDate’ | uppercase }}

=== Implementing custom pipe

[source,typescript]
----
@Pipe({name: 'shorten'})
export class ShortenPipe implements PipeTransform {
  transform(value: any, ...args: any[]): any {
    const maxLength = (args.length === 0 ? 10 : args[0]);

    if (value.length <= maxLength) {
      return value;
    } else {
      return value.substr(0, maxLength - 3) + '...';
    }
  }

}
----

Then add the pipe class to *declarations* in app module.

To reflect data changes in arrays and object for the pipe, use *pure: false* in @Pipe declaration.

=== Filter pipe

Generate stub code for the pipe from command line:

 $ ng g p --no-spec filter

[source,typescript]
----
import {Pipe, PipeTransform} from '@angular/core';

@Pipe({name: 'filter'})
export class FilterPipe implements PipeTransform {
  transform(value: any, filterString: string, propName: string): any {
    if (value.length === 0 || filterString === '') {
      return value;
    }
    return value.filter(item => item[propName] === filterString);
  }
}
----

=== Making a pipe react to data changes:

[source,typescript]
----
@Pipe({
  name: 'filter',
  pure: false
})
----

This might cause performance issues since pipe is applied after every data change.

=== Async pipes

[source,typescript]
----
appStatus = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('stable');
  }, 2000);
});
----

 <h2>App Status: {{ appStatus | async }}</h2>


== HTTP

[source,typescript]
----
private http: Http

const data = { ... }
const headers = new Headers({'Content-Type': 'applcation/json'});
return this.http.post('http://url', data, {
  headers: headers
});
----

To map() and catch():

----
import {catchError, map} from 'rxjs/operators';
import {throwError} from 'rxjs';


private http: HttpClient

this.http.get(this.serviceUrl)
  .pipe(catchError(error => {
      alert('Error when saving recipes: ' + error);
      return throwError(error);
    }
  ))
  .subscribe((data) => {
    alert('Data has been loaded');
  });
----

== Authentication with firebase

 $ npm install --save firebase

In the app.component.ts:

[source,typescript]
----
import * as firebase from 'firebase';'

ngOnInit(): void {
  const config = {
    apiKey: 'AIzaSXCUbQzq0SBkjODl4',
    authDomain: 'ng-recipe-book-2357.firebaseapp.com',
  };
  firebase.initializeApp(config);
}
----

Auth service:

[source,typescript]
----
import * as firebase from 'firebase';

export class AuthService {
  signupUser(email: string, password: string) {
    firebase.auth().createUserWithEmailAndPassword(email, password)
      .catch(error => {
        console.log(error);
        alert('There was an error when signing up: ' + error);
      });
  }

  signinUser(email: string, password: string) {
    firebase.auth().signInWithEmailAndPassword(email, password)
      .catch(error => {
        console.log(error);
        alert('There was an error when signing up: ' + error);
      });
  }
}
----

Firebase rules:

[source,json]
----
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
}
----

Attaching token to the request:

----

----
