= Ansible
:doc-root: https://notes.jdata.pl
:toc: left
:toclevels: 4
:tabsize: 4
:docinfo1:
:icons: font

Sample code: https://github.com/ansiblebook/ansiblebook

.Setting up virtual machine:

[source]
$ vagrant init ubuntu/trusty64
$ vagrant up
$ vagrant ssh-config

.Trying to ssh to virtual machine:

[source]
$ ssh vargant@127.0.0.1 -p 2222 -i private_key

.Telling Ansible about virtual machine:

Edit _hosts_ file (everything should be on one line):

[source]
testserver ansible_host=127.0.0.1 ansible_port=2222 ansible_user=vagrant ansible_private_key_file=private_key

Testing connection:

 $ ansible testserver -i hosts -m ping

Testing conection with verbose output:

 $ ansible testserver -i hosts -m ping -vvvv

== ansible.cfg file

Locations:

. Specified in ANSIBLE_CONFIG environment variable.
. ./ansible.cfg
. ~/.ansible.cfg
. /etc/ansible/ansible.cfg

.Sample ansible.cfg

[source]
----
[defaults]
inventory = hosts
remote_user = vagrant
private_key_file = private_key
host_key_checking = False
----

 $ ansible -m command -a uptime

* -m - module to execute
* -a - module args

[source]
$ ansible testserver -m command -a 'tail /var/log/dmesg'

.Becoming another user

* -b - becoming root user
* --become-user=BECOME_USER - becoming specified user

[source]
$ ansible testserver -b -a 'tail /var/log/syslog'

.Installing nginx on Ubuntu

[source]
$ ansible testserver -b -m apt -a name=nginx

[source]
$ ansible testserver -b -m apt -a "name=nginx update_cache=yes"

.Restarting nginx

[source]
$ ansible testserver -b -a "name=nginx state=restarted"

== Exposing ports through Vagrant

[source]
----
VAGRANT_API_VERSION = "2"

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 443, host: 8443
end
----

[source]
$ vagrant reload

== Simple playbook

[source,yaml]
----
- name: Configure webserver with nginx
  hosts: webservers
  become: True
  tasks:
    - name: Install nginx
      apt: name=nginx update_caches=yes

    - name: Copy nginx config file
      copy: >
        src=files/nginx.conf
        dest=/etc/nginx/sites-available/default

    - name: Enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link

    - name: Copy index.html
      template: >
        src=templates/index.html.j2
        dest=/usr/share/nginx/html/index.html
        mode=0644

    - name: Restart nginx
      service: name=nginx state=restarted
----

.files/nginx.conf

[source]
----
server {
        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;

        root /usr/share/nginx/html;
        index index.html index.htm;

        server_name localhost;

        location / {
                try_files $uri $uri/ =404;
        }
}
----

Jinja 2 template:

.templates/index.html.j2

[source]
----
<html>
<head>
    <title>Welcome to ansible</title>
</head>
<body>
<h1>nginx, configured by Ansible</h1>
<p>If you can see this, Ansible successfully installed nginx.</p>
<p>Running on {{ inventory_hostname }}</p>
</body>
</html>
----

.Running the playbook:

[source]
$ ansible-playbook web-notls.yml

=== Disabling cowsay

[source]
$ export ANSIBLE_NOCOWS=1

or

.ansible.cfg
[source]
----
[defaults]
nocows = 1
----

=== Executable playbooks

shebang:

[source]
#/usr/bin/env ansible-playbook

== Playbooks

Playbook elements:

* a set of _hosts_ to configure
* a list of _tasks_ to execute

A task consists of:

* name - optional comment
* become - if true, tasks are executed by root user
* vars - a list of variables and values

Sample task:

[source,yaml]
- name: install nginx
  apt: name=nginx update_cache=yes

.Modules:

* apt
* copy
* file - sets the attribute of a file, symlink, or directory
* service - starts, stops, or restarts a service
* template - generates a file from a template and copies it to a host

.Ansible documentation:

[source]
$ ansible-doc <module-name>

.Terms relationship:

. Every Playbook executes list of Plays
. Every Play executes on one or more Hosts
. Every Play defines list of one or more Tasks
. Every Task uses one Module

=== Web server with tls

.web-tls.yml

[source,yaml]
----
- name: Configure webserver with nginx and tls
  hosts: webservers
  become: True
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost
  tasks:
    - name: Install nginx
      apt: >
        name=nginx
        update_cache=yes
        cache_valid_time=3600

    - name: Create directories for ssl certificates
      file: >
        path=/etc/nginx/ssl
        state=directory

    - name: Copy TSL key
      copy: >
        src=files/nginx.key
        dest={{ key_file }}
        owner=root
        mode=0600
      notify: Restart nginx

    - name: Copy TLS certificate
      copy: >
        src=files/nginx.crt
        dest={{ cert_file }}
      notify: Restart nginx

    - name: Copy nginx config file
      template: >
        src=templates/nginx.conf.j2
        dest={{ conf_file }}
      notify: Restart nginx

    - name: Enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src={{ conf_file }}
        state=link
      notify: Restart nginx

    - name: Copy index.html
      template: >
        src=templates/index.html.j2
        dest=/usr/share/nginx/html/index.html
        mode=0644

  handlers:
    - name: Restart nginx
      service: >
        name=nginx
        state=restarted
----

Generating a TLS Certificate

[source]
$ openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
  -subj /CN=localhost -keyout files/nginx.key -out files/nginx.crt

.templates/nginx.conf.j2

[source]
----
server {
    listen 80 default_server;
    listen [::]:80 default_server ipv6only=on;

    listen 443 ssl;

    root /usr/share/nginx/html;
    index index.html index.htm;

    server_name {{ server_name }};
    ssl_certificate {{ cert_file }};
    ssl_certificate_key {{ key_file }};

    location / {
        try_files $uri $uri/ =404;
    }
}
----

==== Handlers

. Usually run after all of the tasks are run at the end of the play.
. Always run in the order that they are defined.
. Run once even if notified more than once

=== Multiple Vagrant hosts

[source]
----
VAGRANT_API_VERSION = "2"

ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  # Use the same key for each machine
  config.ssh.insert_key = false

  config.vm.define "vagrant1" do |vagrant1|
    vagrant1.vm.box = "ubuntu/trusty64"
    vagrant1.vm.network "forwarded_port", guest: 80, host: 8081
    vagrant1.vm.network "forwarded_port", guest: 443, host: 8441
    vagrant1.vm.provision "shell" do |s|
      s.inline = <<-SHELL
         echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
         sudo bash -c "echo #{ssh_pub_key} > /root/.ssh/authorized_keys"
      SHELL
    end
  end
  config.vm.define "vagrant2" do |vagrant2|
    vagrant2.vm.box = "ubuntu/trusty64"
    vagrant2.vm.network "forwarded_port", guest: 80, host: 8082
    vagrant2.vm.network "forwarded_port", guest: 443, host: 8442
    vagrant2.vm.provision "shell" do |s|
      s.inline = <<-SHELL
         echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
         sudo bash -c "echo #{ssh_pub_key} > /root/.ssh/authorized_keys"
      SHELL
    end
  end
  config.vm.define "vagrant3" do |vagrant3|
    vagrant3.vm.box = "ubuntu/trusty64"
    vagrant3.vm.network "forwarded_port", guest: 80, host: 8083
    vagrant3.vm.network "forwarded_port", guest: 443, host: 8443
    vagrant3.vm.provision "shell" do |s|
      s.inline = <<-SHELL
         echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
         sudo bash -c "echo #{ssh_pub_key} > /root/.ssh/authorized_keys"
      SHELL
    end
  end
end
----

== Behavioral inventory parameters

Parameters for hosts in inventory file.

[options="header",cols="1,2,7"]
|==========
|Name               |Default        |Description
|ansible_host       |name of host   |hostname or IP
|ansible_port       |22             |
|ansible_user       |root           |User to ssh as
|ansible_password   |(none)         |
|ansible_connection |smart          |How Ansible will connect to host
|ansible_private_key|(none)         |
|ansible_shell_type |sh             |Shell to use for commands
|ansible_python_interpreter|/usr/bin/python|
|ansible_*_interpreter|(none)       |
|==========

.ansible_connection

Trasports:

* `smart` - the default transport, uses locally installed SSH client if it supports
  a feature called _ControlPersist_.
* if _ControlPersist_ is not supported by SSH client, then Ansible usues Python-based SSH client
  library called _Paramiko_.

=== Changing behavioral parameters defaults

You can override some of the behavioral parameter default values in the _defaults_ section
of the _ansible.cfg_:

[options=header]
|=======
|Behavioral inventory parameter|ansible.cfg option
|ansible_port                  |remote_port
|ansible_user                  |remote_user
|ansible_private_key           |private_key_file
|ansible_shell_type            |executable
|=======

== Groups

Ansible automatically defines a group called `all`.

[source]
$ ansible all -a date

Host might appear in more than one group.

.Group of groups:

[source]
----
[group3:children]
group1
group2
----


.Multiple hosts name pattern

[source]
----
[web]
web[1:20].example.com
----

With leading zeros:

[source]
----
[web]
web[01:20].example.com
----

With letters:

[source]
----
[web]
web-[a-t].example.com
----

=== Group variables

Specifying group variables in inventory:

[source]
----
[all:vars]
ntp_server=ntp.ubuntu.com

[production:vars]
db_primary_host=prod-db.example.com

[staging:vars]
db_primary_host=staging-db.example.com
----

=== Host and group variables in their own files

Ansible looks for:

* host variable files in a directory called _host_vars_.
* group variable files in a directory called _group_vars_.

Ansible expects these directories to be either in the directory that contains playbooks or in the directory adjancent
to the inventory file.

== Inventories

=== Dynamic inventory

If the inventory file is an executable file, then Ansible will assume it is a dynamic inventory script and will execute
the file instead of reading it.

Dynamic inventory script must support two command-line arguments:

* --host=<hostname> - fro showing host details
* --list - for listing groups

When ansible runs dynamic inventory script:

[source]
$ ./dynamic.py --host=vagrant2

then output should contain JSON:

[source,json]
{ "ansible_host": "127.0.0.1", "ansible_port": 2200, "ansible_user": "vagrant" }

When:

[source]
$ ./dynamic.py --list

then output should be something like this:

[source,json]
----
{
    "_meta": {
        "hostvars":
    },
    "production": ["host1", "host2"],
    "staging": ["host3", "host3"]
}
----

=== Breaking the inventory into multiple files

Parameter inventory set to directory in ansible cfg:

[source]
----
[defaults]
inventory=inventory
----

You can also use -i flag in command line.

=== Adding entries at Runitme with add_host and group_by

[source,yaml]
----
- name: Provision a vagrant machine
  hosts: localhost
  vars:
    box: trusty64
  tasks:
    - name: create a Vagrantfile
      command: vagrant init {{ box }} creates=Vagrantfile

    - name: Bring up a vagrant machine
      command: vagrant up

    - name: add the vagrant machine to the inventory
      add_host: >
            name=vagrant
            ansible_host=127.0.0.1
            ansible_port=2222
            ansible_user=vagrant
            ansible_private_key_file=/Users/lorin/.vagrant.d/
            insecure_private_key

- name: Do something to the vagrant machine
  hosts: vagrant
  become: yes
  tasks:
    # The list of tasks would go here
    - ...
----

NOTE: creates=Vargant file above is a way of achieving idempotence.

=== group_by module

[source]
----
- name: Group hosts by distribution
  hosts: vagrant
  gather_facts: true
  tasks:
    - name: create groups based on distro
      group_by: key={{ansible_distribution}}

    - debug: msg="groups={{groups}}"
      run_once: true
----

== Variables and Facts

=== Defining Variables

[source]
----
vars:
    key_file: nginx.key
    cert_file: nginx.cert
----

or

[source]
----
vars_files:
  - nginx.yml
----

Showing the value of a variable:

[source]
- debug: var=myvarname

[source]
----
- name: show registered variable
  hosts: vagrant1
  tasks:
    - command: whoami
      register: login
    - debug:
        var: login
    - debug:
        msg: "Logged in as user {{login.stdout}}"
----

Output:
----
TASK [debug] ****************************
ok: [vagrant1] => {
    "login": {
        "changed": true,
        "cmd": [
            "whoami"
        ],
        "delta": "0:00:00.002135",
        "end": "2018-09-11 21:17:14.334920",
        "failed": false,
        "rc": 0,
        "start": "2018-09-11 21:17:14.332785",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "vagrant",
        "stdout_lines": [
            "vagrant"
        ]
    }
}
----

The value of the variable used in `register` is always a dictionary
but the specific keys of the dictionary are different.

==== Ignoring errors

[source]
----
- name: Run myprog
  command: /opt/myprog
  register: result
  ignore_errors: True
- debug: var=result
----

WARNING: If playbook uses registered variables, make sure you know the content
  of the variables for all scenarios (normal, error, etc.)

=== Facts

Printing distro:

[source,yaml]
----
- name: prints out operating system
  hosts: all
  tasks:
    - debug:
        var: ansible_distribution
----

Links:

* https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#information-discovered-from-systems-facts
* https://github.com/lorin/ansible-quickref/blob/master/facts.rst

Printing facts:

[source]
$ ansible host1 -m setup

Filtering facts:

[source]
$ ansible host1 -m setup -a 'filter=ansible_eth*'

Any module can return facts: if a module returns a dictionary
that contains _ansible_facts_ as a key, Ansible will create variable names in the environment with those values
and associate them with the active host.

Getting facts from ec2:

[source]
----
- name: get ec2 facts
  ec2_facts:

- debug: var=ansible_ec2_instance_id
----

==== Local facts

You can associate facts with a host:

* files in `/etc/ansible/facts.d` directory
* formats:
    * ini
    * json
    * executable that takes no arguments and outputs JSON on stdout

These facts are available as keys of variable `ansible_local`.

[source]
----
- name: print ansible_local
  debug:
    var: ansible_local
- name: print book title
  debug:
    msg: "the title of the book is {{ansible_local.example.book}}"
----

==== set_fact

[source]
----
- name: get snapshot id
  shell: >
    aws ec2 describe-snapshots --filters
    Name=tag:Name,Values=my-snapshot
    | jq --raw-output ".Snapshots[].SnapshotId"
  register: snap_result

- set_fact: snap={{ snap_result.stdout }}

- name: delete old snapshot
  command: aws ec2 delete-snapshot --snapshot-id "{{ snap }}"
----

==== Built-in Variables

[options="header",cols="2,8"]
|====
|Parameter                  |Description
|hostvars                   |
|inventory_hostname         |Fully qualified domain name
|inventory_hostname_short   |Name without domain name
|group_names                |A list of all groups that the current host is member of
|groups                     |Maps group name to array of host names.
|ansible_check_mode         |Boolean
|ansible_play_batch         |A list of the inventory hostnames that are active in the
                             current batch.
|ansible_play_hosts         |A list of all hosts active in the current play.
|ansible_version            |Dict with version info.
|====

*hostvars* sample usage:

[source]
{{ hostvars['db.example.com'].ansible_eth1.ipv4.address }}

*groups* sample usage:

[source]
----
backend web-backend
{% for host in groups.web %}
  server {{ hostvars[host].inventory_hostname }} \
  {{ hostvars[host].ansible_default_ipv4.address }}:80
{% endfor %}
----

==== Setting Variables on the Command Line

[source]
$ ansible-playbook example.yml -e token=1234546

Variables set by `-e` have the highest precedence.

Passing a variables file on command line:

[source]
$ ansible-playbook greet.yml -e @greetvars.yml


== Building comlex app

.Listing tasks:

[source]
$ ansible-playbook --list-tasks file.yml

Directory structure:

* logs
* mezzanine
    ** mezzanine_example
* .virtualenvs
    ** mezzanine_example

=== Using iteration

[source,yaml]
----
    - name: install apt packages
      apt:
        pkg: "{{item}}"
        update_caches: true
        cache_valid_time: 3600
      become: True
      with_items:
        - git
        - libjpeg-dev
        - libpq-dev
        - memcached
----

SSH options:

* -f - go to background
* -N - don't execute any command
* -o <option> - available options:
    ** ExitOnForwardFailure=yes
    ** ControlMaster - values

==== Enabling SSH forwarding

Add ssh key to ssh agent:

 $ ssh-add

List agent keys:

 $ ssh-add -l

ansible.cfg:

[source]
----
[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes
----

.Running Mezzanine in development mode

[source,bash]
----
$ sudo apt install git libjpeg-dev libpq-dev memcached nginx postgresql \
  python-dev python-pip python-psycopg2 python-setuptools python-virtualenv supervisor -y
$ sudo pip install pip virtualenv virtualenvwrapper


$ virtualenv venv
$ source venv/bin/activate
$ pip install mezzanine
$ mezzanine-project myproject
$ cd myproject
$ sed -i.bak 's/ALLOWED_HOSTS = \[\]/ALLOWED_HOSTS = ["127.0.0.1"]/' myproject/settings.py
$ python manage.py createdb
$ python manage.py runserver
----

===== Creating Postgres database

[source,yaml]
----
- name: create project locale
  locale_gen: name={{ locale }}
  become: True

- name: create a DB user
  postgresql_user:
    name: "{{ database_user }}"
    password: "{{ db_pass }}"
  become: True
  become_user: postgres

- name: create the database
  postgresql_db:
    name: "{{ database_name }}"
    owner: "{{ database_user }}"
    encoding: UTF8
    lc_ctype: "{{ locale }}"
    lc_collate: "{{ locale }}"
    template: template0
  become: True
  become_user: postgres
----

===== nginx

Cnovention with configuration files:

. Put configuration files in /etc/nginx/conf/sites-available
. symlink to /etc/nginx/sites-enabled


== Roles

Basic structure of a role:

* /roles/database
    ** tasks/main.yml
    ** templates
    ** handlers/main.yml
    ** defaults/main.yml - default variables
    ** vars/main.yml - variables that should not be overridden
    ** meta/main.yml - dependency information about a role

Role locations:

* `roles` dir next to playbook file
* `/etc/ansible/roles` - systemwide roles

Sample roles:

[source,yaml]
----
- name: deploy mezzanine on vagrant
  hosts: web
  vars_files:
    - secrets.yml

  roles:
    - role: database
      database_name: "{{ mezzanine_proj_name }}"
      database_user: "{{ mezzanine_proj_name }}"

    - role: mezzanine
      live_hostname: 192.168.33.10.xip.io
      domains:
        - 192.168.33.10.xip.io
        - www.192.168.33.10.xip.io
----

Using pre-tasks and post-tasks

[source,yaml]
----
- name: deploy mezzanine on vagrant
  hosts: web
  vars_files:
    - secrets.yml
  pre_tasks:
    - name: update the apt cache
      apt: update_cache=yes
  roles:
    - role: mezzanine
      database_host: "{{ hostvars.db.ansible_eth1.ipv4.address }}"
      live_hostname: 192.168.33.10.xip.io
      domains:
        - 192.168.33.10.xip.io
        - www.192.168.33.10.xip.io
  post_tasks:
    - name: notify Slack that the servers have been updated
      local_action: >
        slack
        domain=acme.slack.com
        token={{ slack_token }}
        msg="web server {{ inventory_hostname }} configured"
----

Variable precedence (least to highest):

* role's defaults/main.yml
* play vars section
* role's vars/main.yml
* specified as an argument to a role

Including tasks:
[source,yaml]
----
- name: install apt packages
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  become: True
  with_items:
    - git
    - nginx
- include: django.yml
- include: nginx.yml
----

Conditional task execution - `when`:

[source,yaml]
----
- name: create ssl certificates
  command: >
    openssl req -new -x509 -nodes -out {{ mezzanine_proj_name }}.crt
    -keyout {{ mezzanine_proj_name }}.key -subj '/CN={{ domains[0] }}' -days 3650
    chdir={{ mezzanine_conf_path }}
    creates={{ mezzanine_conf_path }}/{{ mezzanine_proj_name }}.crt
  become: True
  when: tls_enabled
  notify: restart nginx
----

When invoking `copy` Ansible will check the `rolename/files/` directory first.
When invoking `template` Ansible will check the `rolename/templates/` directory first.

=== ansible-galaxy

ansible-galaxy creates scaffolding:

[source]
$ ansible-galaxy init roles/web

== Random ansible features

Controlling failure or changes:

* failed_when
* chanded_when

=== Jinja filters

[source]
{{ hostname|default('localhost') }}

Task filters:

* failed - true if a registered value is a task that failed
* changed
* success
* skipped

File paths filters:

* basename
* dirname
* expanduser - ~ replaced by home directory
* realpath - canonical file path, resolves symbolic links

=== Lookups

* file - file contents
* password - randomly generate a password
* pipe - output of locally executed command
* env - environment variable
* template - Jinja2 template evaluation
* csvfile - entry in a .csv file.
* dnstxt - DNS TXT record
* redis_kv - Redis key lookup
* etcd - etcd key lookup

Example:

----
lookup('file', '/path/to/file.txt')
----

=== Lookups

[options="header",cols="1,3,9"]
|====
|Name               |Input              |Looping strategy
|with_items         |List               |
|with_lines         |Comand to execute  |Loop over lines in command output
|with_fileglob      |Glob               |Loop over filenames
|with_first_found   |List of paths      |
|with_dict          |Dictionary         |Loop over dictionary elements
|with_flattened     |List of lists      |
|with_indexed_items |List               |
|with_nested        |List               |Nested loop
|with_random_choice |List               |
|with_sequence      |Sequence of ints   |Loop over sequence
|with_subelements   |List of dictionaries|Nested loop
|with_together      |List of lists      |Loop over zipped list
|with_inventory_hostnames|Host pattern  |Loop over matching hosts
|====

=== Loop control

[source,yaml]
----
- name: run a set of tasks in one loop
  include: vhosts.yml
  with_items:
    - { domain: www1.example.com }
    - { domain: www2.example.com }
    - { domain: www3.example.com }
  loop_control:
    loop_var: vhost
----

=== Ansible vault

Commands:

* encrypt
* decrypt
* view
* create
* edit
* rekey

== Customizing Hosts, Runs and Handlers

Host definition patterns:

[options="header",cols="3,7"]
|===
|Value          | Example usage
|All hosts      |all
|All hosts      |*
|Union          |dev:staging
|Intersetction  |staging:&database
|Exclusion      |dev:!queue
|Wildcard       |*.example.com
|Range of numbered servers|web[5:10]
|Regular expression|~web\d+\.example\.(com\|org)
|===

Limiting which hosts to run

----
$ ansible-playbook -l hosts playbook.yml
$ ansible-playbook --limit hosts playbook.yml
----
