= AWS Certified Solutions Architect - Associate

https://interactive.linuxacademy.com/diagrams/AWSCSA.html

== Architecture 101

=== Registering

Root user

MFA - Multi-Factor Authentication
Can use Authy or Google Authenticator

Account types:

* professional
* personal

Support plans:

* free
* developer
  ** for early adoption, testing and development
  ** email access to AWS Support during business hours
  ** 1 primary contact can open an unlimited number of support cases
  ** 12-hour response time for nonproduction systems
* business
  ** for production workloads and business-critical dependencies
  ** 24/7 chat, phone, and email access to AWS Support
  ** unlimited contacts can open an unlimited number of
     support cases
  ** 1-hour response time for production systems

Creating a billing alarm in - cloudwatch


== Access Management Basics

* Principal - a person or application that can make an authenticated
  or anonymous request to perform an action on system.
* Authentication - the process of authenticating a principal against
  an identity. This could be via username and password or API keys.
* Identity - objects that require authentication and are authorized
  to access resources
* Authorization - the process of checking and allowing or denying
  access to a resource for an identity

=== Shared Responsibility Model

Responsibilities:

* AWS - security *OF* the cloud
* You - security *IN* the cloud
  ** Encryption at rest and in transit
  ** Network protection
  ** OS, Network and firewall config
  ** Platform, Application, IAM
  ** Customer Data

=== Service models

* IaaS - EC2
* PaaS - only Application and Data layer
* Saas - Netflix, Gmail

System stack:

* Data Center
* Network and storage
* Host/Servers
* Virtualization
* Operating System
* Runtime
* Application
* Data

=== High Availability and Fault Tolerance

High Availability::
  hardware, software, and configuration allowing a system to
  *recover quickly* from failure

Fault Tolerance::
  System designed to *operate through a failure* with
  *no user impact*. More expensive and complex to achieve.

=== Disaster Recovery

Recovery Point Objective (RPO)::
  How much a business can tolerate to lose, experssed in *time*.
  The maximum time between a failure and the last successful backup.

Recovery Time Objective (RTO)::
  The maximum amount of time a system can be *down*.
  How long a solution takes to *recover*.

=== Scaling

*Vertical scaling* is achieved by adding additional resources
in the form of CPU or memory to an existing machine.
By doing so, the machine is able to service additional customers
or perform compute tasks quicker. Eventually, **maximum
machine sizes** will constrain your ability to scale - either
**technically** or from a **cost** perspective.

**Horizontal scaling** is achieved by adding additional machines
into a pool of resources, each of which provide the same service.
Horizontal scaling suffers none of the size limitations of
vertical scaling and can scale to nearly infinite levels but requires
application support to scale effectively.

=== Tiered application

* presentation tier
* logic tier
* data tier

=== Encryption

Types:

* symmetrical
* asymmetrical

----
echo "Cats are Amazing" > hiddenmessage.txt
gpg -c hiddenmessage.txt
cat hiddenmessage.txt.gpg

# this clears the cached password
echo RELOADAGENT | gpg-connect-agent

gpg -o output.txt hiddenmessage.txt.gpg

rm hiddenmessage.txt.gpg
rm output.txt

gpg --gen-key

gpg --armor --output pubkey.txt --export 'Adrian'
gpg --armor --output privkey.asc --export-secret-keys 'Adrian'

gpg --encrypt --recipient 'Adrian' hiddenmessage.txt
gpg --output decrypted.txt --decrypt hiddenmessage.txt.gpg
----

=== Architecture odds and ends

**Cost efficient** or **cost effective**: Implementing a solution within
AWS using products or product features that provide the required service
for as little initial and ongoing cost as possible.
Using your funds effectively and knowing if product X is better or worse
than product Y for a given solution.

**Secure**: In a systems architecture context, implementing a given
solution that secures data and operations as much as possible from
an internal or external attack.

**Application session state**: data that represents what a custome is
doing, what they have chosen, or what they have configured.
Examples include items and quantities in a shopping cart, notes on
an X-ray, and 3D position of a real-time heart scan. Session
state can be stored on a server (**stateful** server) or externally
to a server (**stateless** server).

**Undifferentiated heavy lifting**: A part of an application, system,
or platform that is not specific to your business. Allowing a vendor
(AWS) to handle this part frees your staff to work on adding direct value
to your customers.

== AWS Architecture 101

=== Accounts

AWS account has single root user.

Isolated blast radius.

Multi-account strategies.

By default only root user has rights to access
resources in the account.

Accounts can be linked and configured to allow
**consolidated billing** where a **master** account is charged for all
**member** account resource usage.

=== AWS Physical and Networking Layer

AWS Region
* data stored in specific country.

us-east-1 - US East (N. Virginia)
us-east-2

Most product operate in a region-isolated way.

Region contain availability zones (AZs), which are separated and
isolated networks. A failure in one AZ generaly **won't impact
another**.

AZs in the same region are connected with **redundant**, **high-speed**,
**low-latency** network connections.

Most AWS services run within AZs. Some services operate from one AZ,
while other s replicated between AZs. Some services allow you to chose
the AZ to use, and some don't.

**Edge locations** are small pockets of AWS compute, storage,
and network close to major populations and are generally used
for **edge computing** and **content delivery**.


=== AWS Well-Architected Framework

AWS Well-Architected Framework is a set of documents.

Pillars:

* Security
    ** Implement a strong identity foundation.
    ** Enable traceability.
    ** Apply security at all layers.
    ** Automate security best practices.
    ** Protect data in transit and at rest.
    ** Prepare for security events.
* Reliability
    ** Test recovery procedures.
    ** Automatically recover from failure.
    ** Scale horizontally to increase aggregate system availability.
    ** Stop guessing capacity.
    ** Manage change in automation.
* Performance Efficiency
    ** Democratize advanced technologies.
    ** Go global in minutes.
    ** Use serverless architectures.
    ** Experiment more often.
    ** Mechanical sympathy.
* Operational Excellence
    ** Perform operations as code.
    ** Annotate documentation.
    ** Make frequent, small, reversible changes.
    ** Refine operations procedures frequently.
    ** Anticipate failure.
    ** Learn form all operational failures.
* Cost Optimization
    ** Adopt a consumption model.
    ** Measure overall efficiency.
    ** Stop spending money on data center operations.
    ** Analyze and attribute expenditure.
    ** Use managed services to reduce cost of ownership.


== AWS Product Fundamentals

=== S3

S3 is a global service.

* Bucket name has to be unique globally across
  all regions and all accounts.
* Files are replicated across availability zones
  in the region.
* buckets have flat structure.
* object names are unique within a bucket
* file size up to 5TB
* By default, there's a limit of 100 buckets

=== CloudFormation

Formats: JSON, YAML

. Template - contains **logical** resources and configuration.
. Stack - created and modified basing on templates.
. Physical resources - stacks take **logical resources** from
  template and create, update, or delete the **physical resource**
  in AWS.

Template sections:

* AWSTemplateFormatVersion
* Description
* Metadata
* Parameters
* Mappings
* Conditions
* Transform
* Resources
* Outputs

Example:

[source]
----
{
  "Resources": {
     "catpics" : {
        "Type": "AWS::S3::Bucket"
     }
  }
}
----

Key points:

* CFN template is written in JSON or JAML
* a template can create up to 200 resources
* if a stack is deleted, then by default, any resources
  it has created are also deleted.
* a stack can be updated by uploading new version of a template.
* new logical resources cause new physical resources.
* removed logical resources cause the stack to delete the
  physical resources
* changed logical resources update with some disruption or replace
  physical resources.

== IAM (Identity and Access Control)

ARN - Amazon Resource Name

ARN always begin with:

 arn:partition:service:region:account-id:

* partition - *aws* or *aws-cn* (for China)
* service - the AWS service: *s3*, *ec2*, *rds*, *dynamobd*
* region - region-code: *us-east-1*, *ap-southeast-2*

Example arns:

 arn:aws:iam::123456789012:user/roffle
 arn:aws:s3:::myamazingcatpics/truffs.jpeg
 arn:aws:dynamodb:us-east-1:123456789012:table/ratemycats

Credentials:

* username and password
* access keys
* short term credentials - used by roles

By defalut IAM identity has no permissions.

=== IAM policies

Types:

* identity policy
* resource policy

Policy has no effect until it is  attached to something.

Policy document is a list of *statements*:

[source]
----
{
  "Version": "2019-10-17",
  "Statement": [
    {
      "Sid": "SpecificTable",
      "Effect": "Allow",
      "Action": [
        "dynamodb:BatchGet",
        "dynamodb:DescribeStream",
        "dynamodb:DescribeTable",
        "dynamodb:Get*",
        "dynamodb:Query",
        "dynamodb:Scan",
        "dynamodb:BatchWrite*",
        "dynamodb:CreateTable",
        "dynamodb:Delete*",
        "dynamodb:Update*",
        "dynamodb:PutItem"
      ],
      "Resource": "arn:aws:dynamodb:*:*:table/CatPics"
    }
  ]
}
----

When there is no explicit permision, than there's implicit default deny.

Explicit deny -> Explicit allow -> Implicit deny

Exam hints:

* hard limit of 5k IAM users per account.
* 10 group memberships per IAM user
* default maximum of 10 managed policies per user
* no inline limit, but you cannot exceed 2048 characters for all
  inline policies on an IAM user.
* 1 MFA per user
* 2 access keys per user

=== Groups

* Groups are admin feature to group IAM users.
* Groups can contain many IAM users, and users can be in many groups.
* Groups are not **true** identities, they cannot be referenced
  from resource policies.
* Groups have no credentials.

=== Access keys

Access key consist of:

* Access Key ID
* Secret Access Key

Max 2 access keys per user.

You cannot authenticate to management console
with access keys.

In My Account activate:
"IAM User and Role Access to Billing Information"
to be able to give users access to billing information.

=== AWS CLI

 $ aws configure

To configure access keys.

 $ aws configure --profile test-user
 $ export AWS_PROFILE=test-user

=== Roles

Roles are *assumed* by another identity allowed
in the *trust policy*:

* IAM user
* AWS service
* another AWS account
* web identity
* anonymous identity

When role is assumed, the Security Token Service
(*STS*) generates a **time-limited** set of access
keys (temporary security credentials).

These access keys have the permissions defined in the permission policy.
IAM roles have no long-term credentials (access keys
or username and password).

Every role has two policies:

* trust policy - controls who can assume the role
* permission policy - policy that gives the role permission on things

Paterns:

* to gain additional permissions only when you need it
* service accesss
* for granting permissions to users from another AWS account
* multiple AWS accounts in the company - single IAM account

== Multi-Account Management and Ogranizations

**AWS Organizations** is a service for managing
**multiple accounts** within a single business.

All accounts within an AWS Organization can
**consolidate bills** into a single account.

Organizations can share bulk discounts and manage
accounts and permissions and limit account usage using **service control policies**.

* master account
* member accounts

Base limit is 2 accounts within an organization.

FullAWSAccess - service control policy allowing access to
all AWS services within an attached member account.

== EC2 Fundamentals

Instance Store Volume is not persisted in case of failure.

Security Group - protocol, port

CloudWatch - 5 min granularity.
Can enable 1 min granularity with **Detailed Monitoring**,
but associated with extra cost.

Instance states:

* running
* stopped
* pending
* stoping

Billed by the second with the minimum of 50 seconds.

=== Instance types

Instance families:

* general purpose
* compute optimized
* memory optimized
* accelerated computing
* storage optimized

Instance types:

* **T2**, **T3** - low-cost with burst capability
* **M5** - for general workloads
* **C5** - cpu
* **X1**, **R4** - memory
* **I3** - fast IO
* **P2**, **G3**, **F1** - GPU and FPGA

Instance sizes:

* nano
* micro
* small
* medium
* large
* x.large
* and larger 2xlarge, 4xlarge...

Special cases:

* a - AMD CPU
* A - Arm based
* n - higher speed networking
* d - NVMe storage

=== Storage

SAN or NAS - block storage

EBS (Elastic Block Storage) is a storage service that
**creates and manages volumes**.

Volumes are:

* persistent
* can be attached and removed to EC2 instances
* are replicated within a single AZ

**Instance store volumes**:
* are attached to EC2 host.
* Known as **ephemeral devices**.
* Best storage perforamnce
* when the host fails, the storage is lost
* should be regarded as temporary
* example: storage optimized instance types

Attaching storage:

----
$ lsblk
$ sudo mkdir /ephemeral
$ sudo mkfs -t ext4 /dev/nvme1n1
$ sudo mount /dev/nvme1n1 /ephemeral
----

When doing instance-level reboot emphemeral storage
is maintained.

After stopping and starting ephemeral storage is lost.

Volume types:

* **standard** - magnetic
* **sc1** - Cold HDD - lowest cost, infrequent access, can't be boot volume.
* **st1** - Throughput Optimized - low cost, throughput intensive, can't be a boot volume.
* **gp2** - general purpose SSD - default, balance of IOPS/MiB/s - burst pool IOPS per GB
* **io1** - Provisioned IOPS - highest performance, can adjust size and IOPS separately


To protect against AZ failure, EBS snapshots (to S3)
can be used.
Data is replicated across AZs in the region and
(optionally) internationally.

IOPS - number of input and output operations that storage can
perform in a given second.

Throughput - data rate.

gp2:

* you get 3 IOPS per every GB of volume size
* burst up to 3k IOPS
* minimum 100 IOPS
* max 16k IOPS
* burst pull - you get 5.4 million starting credits

io1:

* size and IOPS set separately
* max 64k IOPS for volumes
* max throughptu per volume 1k MiB/s

Facts:

* EBS supports a maximum per-instance throughput of 1,750 MiB/s
  and 80k IOPS.

=== Snapshots

Inconsistent snapshot - when the instance is runnig.

Options for conistent snapshot:

* flush any in-memory caches to disk
* stop instance for root volume snapshots

Sharing snapshots:

* by default snapshot is private
* you can share snapshot with specific AWS accounts
* You can enable public access
* you can copy the snapshot to another region

Data Lifecycle Manager:

* shedule and manage the creation and deletion of EBS snapshots

Snapshots are stored in S3.

Snapshots are stored incrementally.

=== Security groups

Every instance is created with its default ENI
(Elastic Network Interface).

Security groups are  software firewalls that can be attached to network interfaces
and (by association) products in AWS.

Security groups each have inbound rules and outbound rules.

A rule allows traffic to or from a source (IP, network,
named AWS entity) and protocol.

Security groups have a hidden implicit/default deny rule, but
**cannot explicitly deny traffic**.

Security groups are stateful - any traffic allowed in/out,
the return traffic is automatically allowed.

Security groups can reference:

* AWS resources
* other security groups
* themselves

Max 5 security groups for every ENI.

Security group belongs to VPC.

=== Instance metadata

http://169.254.169.254/latest/meta-data
http://169.254.169.254/latest/meta-data/ami-id
http://169.254.169.254/latest/meta-data/instance-id
http://169.254.169.254/latest/meta-data/instance-type

=== AMI

Amazon Machine Image

They store:

* snapshots of EBS volumes
* permissions
* block device mapping

AMIs can be shared, free, or paid and can be copied
to other AWS regions.

Types of AMIs:

* Instance store backed AMIs
* EBS backed AMIs

Snapshots are created when creating AMI.

AMI permissions:

* defaults to private
* can be public
* can be shared with specific AWS accounts

Bootstrapping:

* user data script
* cloud-init config

=== EC2 Networking Fundamentals

* public instance - with public IP
* private instance - only can be communicated inside the VPC

Private IP addresses don't change when instance
is stopped.

Public ip doesn't change at restart.

Public ip changes when instance is stopped and started.

=== EC2 Instance roles

EC2 **instance roles** are IAM roles that can be assumed by EC2 using an
intermediary called an **instance profile**.

An instance profile:

* is either created automatically when using the console UI
  or manually when using the CLI.
* is a container for the role that is associated with an EC2 instance.
* allows applications on the EC2 instance to access the credentials
  the role using the **instance metadata**.

Credential order:

. Command line options:
+
 $ aws [commond] --profile [profile-name]
+
. Environment variables: AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY, AWS_SESSION_TOKEN.
+
Recommended for temporary use in non-production
environments.
+
. AWS CLI credentials file
+
  $ aws configure
+
. container credentials
+
IAM Roles associated with AWS Elastic Container Service (ECS)
Task Definitions.
Temporary credentials are available to the Task's containers.
This is **recommended** for ECS environments.
+
. Instance Profile Credentials
+
IAM Roles associated with EC2 instances via
Instance Profiles.
This is recommended for EC2 environments.

=== Lab

==== To create role

Create file _trust_policy_ec2.json_

[source,json]
----
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {"Service": "ec2.amazonaws.com"},
      "Action": "sts:AssumeRole"
    }
  ]
}
----

To create role:

 $ aws iam create-role --role-name DEV_ROLE --assume-role-policy-document file://trust_policy_ec2.json

==== Create managed policy

Create file _dev_s3_read_access.json_

[source,json]
----
{
    "Version": "2012-10-17",
    "Statement": [
        {
          "Sid": "AllowUserToSeeBucketListInTheConsole",
          "Action": ["s3:ListAllMyBuckets", "s3:GetBucketLocation"],
          "Effect": "Allow",
          "Resource": ["arn:aws:s3:::*"]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:Get*",
                "s3:List*"
            ],
            "Resource": [
                "arn:aws:s3:::<DEV_S3_BUCKET_NAME>/*",
                "arn:aws:s3:::<DEV_S3_BUCKET_NAME>"
            ]
        }
    ]
}
----

 $ aws iam create-policy --policy-name DevS3ReadAccess --policy-document file://dev_s3_read_access.json

==== Attach policy to role

 $ aws iam attach-role-policy --role-name <role-name> --policy-arn <policy-arn>

 $ aws iam list-attached-role-policies --role-name <role-name>

 $ aws iam get-policy --policy-arn <policy-arn>

 $ aws iam get-policy-version --policy-arn <policy-arn> --version-id <policy-version>

==== Create instance profile

 $ aws iam create-instance-profile --instance-profile-name DEV_PROFILE

 $ aws iam add-role-to-instance-profile --instance-profile-name <profile-name> --role-name <role-name>

 $ aws iam get-instance-profile --instance-profile-name <profile-name>

==== Attach instance profile to EC2 instance

----
$ aws ec2 associate-iam-instance-profile --instance-id i-03d70110f4b012e08 --iam-instance-profile Name=DEV_PROFILE

{
    "IamInstanceProfileAssociation": {
        "InstanceId": "i-03d70110f4b012e08",
        "State": "associating",
        "AssociationId": "iip-assoc-06a940e64e14b97e8",
        "IamInstanceProfile": {
            "Id": "AIPA367XEJHYAYVDRPIIN",
            "Arn": "arn:aws:iam::822467643888:instance-profile/DEV_PROFILE"
        }
    }
}
----

 $ aws describe-instances --instance-ids <instance-id>

==== Verifying role association

SSH into target host.

----
$ aws sts get-caller-identity

{
    "Account": "822467643888",
    "UserId": "AROA367XEJHYJ6MOLSVSB:i-03d70110f4b012e08",
    "Arn": "arn:aws:sts::822467643888:assumed-role/DEV_ROLE/i-03d70110f4b012e08"
}
----

=== Lab - tagging

* Tag Editor: https://docs.aws.amazon.com/ARG/latest/userguide/tag-editor.html
* Tagging Strategies: https://aws.amazon.com/answers/account-management/aws-tagging-strategies/
* Tagging and Cost Allocation: https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/cost-alloc-tags.html#allocation-what
* AWS Resource Groups: https://docs.aws.amazon.com/ARG/latest/userguide/welcome.html
* AWS Systems Manager: https://docs.aws.amazon.com/systems-manager/latest/userguide/what-is-systems-manager.html
* AWS Config: https://docs.aws.amazon.com/config/latest/developerguide/WhatIsConfig.html

Tagging categories:

. Technical tags
  .. Name
  .. ApplicationId
  .. ApplicationRole
  .. Cluster
  .. Environment
  .. Version
. Tags for Automation:
  .. Date/Time
  .. Opt in/Opt out - used to indicate whether a resource
     should be automatically included in an automated activity,
     such as starting, stopping, or resizing instances.
  .. Security
. Business Tags
  .. Owner
  .. Cost Center/Business Unit
  .. Customer
  .. Project
. Security Tags
  .. Confidentiality
  .. Compliance

== Advanced

=== Volume encryption

Volume encryption uses EC2 host hardware to encrypt data **at rest** and
**in transit** between EBS and EC2 instances.

Encryption generates a data encryption key (**DEK**) from a customer
maste key (**CMK**) in each region.

A unique DEK encrypts each volume.

Snapshots of that volume are encrypted with the **same DEK**, as are any volumes
created from that snapshot.

KMS manages DEKs.

KMS - Key Management Service

KMS is regional service.

Every key starting with "aws/" is AWS-managed customer master key (CMK).

You cannot create unencrypted snapshot from encrypted volume.

The snapshot will be encrypted with same data encryption key that was used
in the volume. Same for volumes created from the snapshot.

=== Networking

Traditionally, virtual networking meant an EC2 host arranging access
for _n_ virtual machines to access one physical card - this multitasking
is done in software and is typically slow.

**Enhanced networking** uses SR-IOV (Single Root IO Virtualization), which
allows a single physical metwork card to appear as multiple physical devices.
Each instance can be given one of these (fake) physical devices.
This results in **faster transfer rates**, **lower CPU usage**, and **lower
consistent latency**.

EC2 delivers this via the Elastic Network Adapter (ENA) or Intel
62599 Virtual Function (VF) interface.

=== Placement groups

**Cluster Placement Groups** place instances physically near each other in a single AZ.

Every instance can talk to every other instance at the same time at
full speed.

Works with enhanced networking for peak performance.

**Partition PGs** - instanced deployed into a Partinion PG (PPG) are separated
into partitions (max of seven per AZ), each occupying
isolated racks in AZs/regions.

PPG can span multiple AZs in a region.

PPGs minimize failure to a partition and give you visibility on placement.

**Spread PGs** (SPG) - purely for availability.

SPGs are designed for a max of seven instances per AZ that need to be
separated.

Each instance occupies a partition and has an isolated fault domain.

Gread for email servers, domain controllers, file servers, and application HA pairs.

=== Billing

**On demand** - per second with minimum 60 seconds.

**Spot instances** allow **conumption of spare AWS capacity** for a given instance type and size in a specific AZ.

Instances are provided as long as your bid price is above the spot price, and you only ever pay the spot price.

If your bid is exceeded, instances are terminated with a two-minute warning.

Spot fleets are a container for "capacity needs." You can specify pools
of instances of certain types/sizes aiming for a given "capacity".
A minimum percentage of on-demand can be set to ensure the fleet is always active.

Spot instances are perfect for non-critical workloads, burst workloads,
or consistent non-functional jobs that can tolerate interruptions
without impacting functionality.

Spot is **not suitable** for long-running workloads that require
stability and cannot tolerate interruptions.

**Reserved instances** lock in a reduced rate for **one** or **three**
years.

**Zonal** reserved instances include a **capacity** reservation.

**Regional** reservation doesn't have capacity reservation.

Your commitment incurs costs even if instances aren't launched.

Reserved purchases are used for long-running, understood, and consistent workloads.

Reserved instances payment options:

* No upfront
* Partial upfront
* All upfront

**Dedicated hosts** - physical hardware reservation.

You need to specify:

* instance type (eg. m5d.large)
* AZ
* Host recovery - when checked, EC2 instances on failed hosts will be transfered
  to new host, assuming you have one.

Reasons to use dedicated host:

* compliance and mandatory reasons.
* bring your own licence (BOYL)
* control instance placement

== Serverless achitecture

=== Event-driven architecture

When using event-driven architecture, a system
operates around "events" that represent **an
action or a change of state** - e.g. a button being clicked,
a file being uploaded, etc.

* much more efficient use of resources

Serverless architecture components:

* BAS - backend as a service - using third-party services where possible
  rather than runing your own. Examples: Auth0 or Cognito for
  authentication and Firebase or DynamoDB for data storage.
* FAS - function as a service - functions are only active (invoked)
  when they are needed (when event is received).

=== Lambda

Functions are code, which run in a runtime.

Functions are invoked by **events**, perform actions for up to **15 minutes**,
and terminate.

Functions are **stateless**.

Function assume role when running.

Event-based invocation (including time events).

Lambda function needs to to have unique name in the region in the account.

Minimum billed duration is 100 ms.

Memory: 128MB to 3008MB.

Timeout value - hard limit - max 15 minutes.

=== API Gateway

Pricing is based on the number of API calls, the data transfered and any caching
required to improve performance.

API Gateway can access some AWS services directly using proxy mode:

* EC2 (backed by EBS) - monolith
* Fargate (backed by Aurora) - microservice
* Lambda (backed by DynamoDB) - serverless

You can attach DynamoDB to API gateway.

API protocol:

* REST
* WebSocket

Endpoint type:

* Regional
* Edge optimized
* Private

You can enable CORS support on resource level.

To have API active you have to deploy it.

API can belong to muliple stages (prod, dev, test, v1, v2, etc.)

=== Step functions

Step Functions is a **serverless visual workflow service** that provides
**state machines**.

A state machine can orchestrate other AWS services with simple logic, branching,
and parallel execution, and it maintains a **state**.

Workflow steps are known as **states**, and they can perform work via **tasks**.

Step Functions allows for **long-running serverless workflows**.

A state machine can be defined using Amazon States Language (**ASL**).

Step Function runs for one year.

== Container-based compute and microservices

To install Docker on Amazon Linux 2:

 $ sudo amazon-linux-extras install docker
 $ sudo service docker start
 $ sudo chkconfig docker on
 $ sudo usermod -aG docker $USER

=== ECS - Elastic Container Service

Based on docker.

Modes:

Core components:

* Scheduling and Orchestration
* Cluster Manager
* Placement Engine

ECS cluster is a container of configuration.

EC2 based:

* EC2 Windows + Networking
* EC2 Linux + Networking

Fargate based - serverless approach:

* Networking only

Components: task definitions, tasks and services.

== Networking

OSI networking model:

1. physical (copper, fiber-optic, radio frequency)
2. data link (MAC addresses, frames)
3. network (ip addressing - addressing that can cross network boundaries)
4. transport (reliability)
5. session (response communication)
6. presentation (tls, conversion, encryption, compression and standards)
7. application (http, ssh, ftp)

Transport layer:

* TCP
  ** aimed for reliable transport
  ** uses *segments* to ensure data is received in the **correct order**
  ** adds **error checking**
  ** adds **ports** allowing different streams of communications to the same host
* UDP - aimed for speed

=== IP Addressing

32-bit value

x.x.x.x - four octects

Two parts: network and host.

Reserved IP addresses:

* 0.0.0.0 & 0.0.0.0/0 - all ip addresses
* 255.255.255.255 - breadcast address
* 127.0.0.1 - localhost (loopback) address
* 169.257.0.1 to 169.254.255.254 - a range of IP addresses which
  a device can auto configure with if its using DHCP and fails
  to automatically get an IP from a DHCP server.

IP address classes:

* A (/8) - 1.0.0.0 to 126.255.255.255 - 126 networks
* B (/16) - 128.0.0.0 to 191.255.255.255 - 16 382 networks
* C (/24) - 192.0.0.0 to 223.255.255.255 - 2 097 150 networks

Private address ranges:

* 10.0.0.0 to 10.255.255.255 - Class A
* 172.16.0.0 to 172.31.255.255 - Class B
* 192.168.0.0 to 192.168.255.255 - Class C

Private address ranges cannot be used directly over internet.

**CIDR** - Classless Inter-Domain Routing

=== Subnetting

Subnet cannot span across AZs.

=== IP routing

Scenario 1 - local:

* devices are on the same network
* Communication on layer 2 level
* networking stack does ARP (address resolution protocol)
* ARP request on local network for MAC address

Scenario 2 - separate subnets:

* on Layer 3 - it's single communication
* on Layer 2 - it's communication to/from router
* default gateway - an IP used to send data off the local network
* A to B communication:
** A generates L3 packet - the SRC is the IP-A, the DST is IP-B
** A knows its default gateway IP, so it uses ARP to find the Router MAC
** A passess the L3 packet to L2, wraps it in a L2 frame and
   sends this to the Router -MAC addresss
** Router receives this, strips away the L2 frame, checks the DST IP
** it konws the network of IP-B because it's connected to it
** R uses ARP to find the MAC of B, generates a frame to B, ptus the
   unaltered IP packet inside and sends to MAC-B
** B receives the frame, strips it away, and passes the packet to L3

Scenario 3 - over Internet

* communication over Internet uses BGP - Border Gateway Protocol
* BGP exchanges routes

==== Firewalls

Firewall establish a barrier between networks of different security levels
and historycally have been the first line of defence against
perimeter attacks.

What data a firewall can read and act on depends on the OSI Layer the firewall
operates at:
* Layer 3 (Network) - source/dest IP addresses or ranges
* Layer 4 (Transport) - Protocol (TCP/UDP) and port numbers
* Layer 5 (Session) - as layer 4, but understand response traffic
* Layer 7 (Application) - application specifics, e.g. HTML paths, images

==== Proxy server

* Handles outgoing traffic.
* can filter out content
* acts as a web cache

== VPC

Types:

* custom VPC
* default VPC

Default VPC:

* CIDR 172.31.0.0/16
* subnet created in every AZ - /20 subnet (4091 available addresses)
* default DHCP option set attached
* default SG - all from itself, all outbound
* default NACL - all inbound and outbound

Custom VPCs:

* CIDR min /16, max /28
* Tenancy: default or dedicated

Special addresses:

* .0 - network address
* .1 - router address
* .2 - DNS
* .3 - reserved for future use
* .X - breadcast address - last address in subnet

DHCP option sets:

* VPC can have only one DHCP option set associated with it

You can share subnet with other AWS account:

* you can share subnet within AWS organization
* other account can only deploy resources into subnet, it cannot modify its settings

==== Routing

Every VPC has a virtual routing device called the VPC router.

It has an interface in any VPC subnet known as the "subnet+1"
addresss - for 10.0.1.0/24 this would be 10.0.1.1.

The router is highly available, scalable, and controls data entering and
leaving VPC and its subnets.

Each VPC has a "main" route table, which is allocated to all subnets in the VPC by default. A subnet must
have one route table.

Additional "custom" route tables can be created and associated with subnets - but only
one route table per subnet.

A route table controls what the VPC courer does with traffic leaving a subnet.

An internet gateway is created and attached to a VPC (1:1). It can
route traffic for public IPs to and from the internet.

Poutes:

A Router is a collection of routes that are used when traffic from
when traffic from a subnet arrives at VPC

Every route table has a local route, which matches the CIDR of the VPC
and lets traffic be routed between subnets.

A route contains a destination and a target. Traffic
is forwarded to the target if its destination matches
the route destination.

If multiple routes apply, the most specific is chosen.

Targets can be IPs ar AWS networking gateways/objects.

A subnet is a public subnet if:

* subnet is configured do allocate public IPs (but it can be
  overriden when deploying instance to the subnet)
* the VPC has an associated Interent Gateway
* subnet has a default route to that internet gateway.

**Internet gateway**:

* needs to be attached manually to
  specific VPC after creation.
* can only be attached to one VPC
* VPC can have at most one internet gateway
* gateway does **static network address translation** (static NAT)

Route propagation:

VPG - can propagate any routes from the route table
  to VPG.

=== Bastion host

private dns: ip-x-x-x-x.ec2.internal
public dns: ec2-18-205-247-220.compute-1.amazonaws.com

=== NAT

Static NAT - a private IP is mapped to a public IP (what IGWs do)

Dynamic NAT - a range of private addresses are mapped
onto one or more public (used by your home router and NAT gateways).

AWS:

* NAT gateways
* NAT instances

NAT gateway

* must be placed in public subnet
* must have elastic IP assigned
* are not high available
* must be placed in a single subnet
* scale with load
* initially supports over 5Gb of bandwidth, can scale up to 45Gb

To have NAT instance working you have to disable **Source and destination check**

=== Network Access Control Lists (NACL)

NACL operate at Layer 4 of the OSI model (TCP/UDP) and below.

A subnet has to be associated with a NACL - either the VPC default
or custom NACL.

NACLs only impact craffic crossing the boundary of a subnet.

NACLs are collections of rules that can explicitly allow or deny
traffic based on its protocol, port range, and source/destination

Rules are processed in number order, lowes first. When a match is
found, that action is taken and processing stops.

The "*" rule is processed last and is an implicit **deny**.

NACLs have two sets of rules: inbound and outbound.

**Ephemeral ports**:

* when a client initiates communications with a server, it is to a well-known
  port number on that server
* the response is from that well-known port to an ephemeral port on the client.
  The client decides the port.
* NACLs are stateless, they have to consider **both** initiating and
  response traffic - tsate is a session-layer concept.

* practical range of ephemeral ports: 1024-65535

=== Creating VPC

. Create VPC
. Create subnets
. Set __Auto-assign public IPs__ for public subnets.
. Add Internet Gateway and assign it to the VPC.
. Create route table which routes to Internet Gateway
. Associate public subnets with public route table.



== Todo list

* Read Well architecture framework whitepaper.
* Websockets:
    ** https://docs.aws.amazon.com/apigateway/latest/developerguide/welcome.html
    ** https://tools.ietf.org/html/rfc6455


Questions: what is the pricing of NAT Gateways?
