= CXF
:doc-root: https://notes.jdata.pl
:toc: left
:toclevels: 4
:tabsize: 4
:docinfo1:
:icons: font

== Basics

Artifact `org.apache.cxf:cxf-rt-frontend-jaxws:3.2.6`:

* provides JAX-WS implementation to replace the built-in JDK one
* contains `META-INF/services/javax.xml.ws.spi.Provider` file

Artifact `org.apache.cxf:cxf-rt-transports-http-jetty:3.2.6`:

* if you don't use a servlet container.

=== Acronyms

SOAP::
 Simple Object Access Protocol - XML-based standard protocol
 for web services.

WSDL::
 Web Service Description Language - service description: method
 names, port types, service endpoint, binding, method params etc.

UDDI::
 Universal Description, Discovery and Integration - directory
 of web services where clien applications can lookup for web
 services. Web services can register to the UDDI server and make
 them available to client applications.

JAX-WS::
 Java API for XML Web Services. Part of standard Java API.

=== wsimport

Use `wsimport` utility to generate client stubs.

 $ ws import -s . http://localhost:8888/ws/person?wsdl

== Implementing web service

Maven:

[source,xml]
<dependencies>
    <dependency>
        <groupId>org.apache.cxf</groupId>
        <artifactId>cxf-rt-frontend-jaxws</artifactId>
        <version>3.1.6</version>
    </dependency>
</dependencies>

`cxf-rt-frontend-jaxws` jar contains
`META-INF/services/javax.xml.ws.spi.Provider` file, which
determine the JAX-WS implementation.

== Web service security

Tutorial: https://sites.google.com/site/ddmwsst/

=== Concepts

Data privacy:

* encryption / decryption
* translate - to change crypto keys

Data integrity, authenticity and non-repudation:

* Hash (Message Digest)
* MAC (Message Authentication Code)
* HMAC (Hash MAC)

Key management and distribution: storage, retrieval and key form
conversions:

* import operation
* export operation

==== Cryptography providers

JCA - Java Cryptography Architecture
JCE - Java Cryptography Extension

Installing a provider:

* dynamically at runtime
* configure JRE to preload the provider
* SunJCE is the default provider that is shipped with JRE
* Bouncy Castle - well known provider

Installing by configuring the JRE:

. put jar files in jre/lib/ext directory
. update jre/lib/security/java.security file:
+
[source]
----

# List of providers and their preference orders (see above):
#
security.provider.1=sun.security.provider.Sun
security.provider.2=com.sun.net.ssl.internal.ssl.Provider
security.provider.3=com.sun.rsajca.Provider
security.provider.4=com.sun.crypto.provider.SunJCE
----
+
. ueoht

Installing at runtime:

[source,java]
----
import java.security.Security;
import org.bouncycastle.jce.provider.BouncyCastleProvider;

...

Security.addProvider(new BouncyCastleProvider());
----

=== Certificates

Certificate purposes:

* Encryption - contains keys for encryption and decryption
* Signature - contains keys fro signing data only
* Signature and encryption
* Signature and smpartcard logon - allows for initial logon with
  a smartcard and digitally signing data, it cannot be used
  for data encryption

CA - Certificate Authority

