= Kubernetes Up and Running book notes

== Limiting resources

----
$ docker run -d \
    --name test \
    -p 8080:8080 \
    --memory 200m \
    --memory-swap 2G \
    --cpu-shares 1024 \
    nginx
----

== Common kubectl commands

 $ kubectl config sen-context my-context --nameplace=mystuff
 $ kubectl config use-context my-context

[options=header,cols=2]
|===
|Option|Description
| -o wide | wide columns
| --no-headers |skip headers
| -o jsonpath --template={.status.podIP}
|===

 $ kubectl apply -f file.yaml

To check what would be changed:

 $ kubectl apply --dry-run -f file.yaml

To edit interactively:

 $ kubectl edit <resource-name> <object-name>

Deleting an object:

 $ kubectl delete -f obj.yaml
 $ kubectl delete <resource-name> <object-name>

=== Labeling

 $ kubectl label pods bar color=red
 $ kubectl annotate pods bar annotation=value

Removing a label:

 $ kubectl label pods bar color-

=== Debugging commands

 $ kubectl logs <pod-name>
 $ kubectl logs <pod-name> -c <container-name>

-f - follow

Running commands in the container:

 $ kubectl exec -it <pod-name> -- bash

Attaching to the container:

 $ kubectl attach -it <pod-name>

Copying files to and from a container:

 $ kubectl cp <pod-name>:</path> <local-path>

Forwarding a port:

 $ kubectl port-forward <pod-name> 8080:80

To enable auto-completion:

 $ sudo apt install bash-completion
 $ source <(kubectl completion bash)

== Labels and annotations

Labels - arbitrary, identifying info.

Annotations - hold nonidentifying info that can be
used by tools and libraries.

 $ kubectl create deployment alpaca-prod --image=gcr.io/kuar-demo/kuard-amd64:blue
 $ kubectl label deployment alpaca-prod ver=1 app=alpaca env=prod --overwrite

 $ kubectl get deployments

Selectors:

 $ kubectl get pods --selector="ver=2"
 $ kubectl get pods -l ver=2
 $ kubectl get pods -l "app in (alpaca,bandicoot)"

Getting objects with label defined:

 $ kubectl get pods -l <label-name>

Selector operators:

* key=value
* key!=value
* key in (value1,value2)
* key notin (value1,value2)
* key
* !key

=== Label selectors in API objects

[source,yaml]
----
selector:
  matchLabels:
    app: alpaca
  matchExpressions:
    - {key: ver, operator: In, values: [1, 2]}
----

== Service Discovery

Exposing a service:

----
$ kubectl expose deployment <deployment-name>
----

----
$ ALPACA_POD=$(kubectl get pods -l app=alpaca \
  -o jsonpath='{.items[0].metadata.name}')
$ kubectl port-forward $ALPACA_POD 48858:8080
----

DNS:

alpaca-prod.default.svc.cluster.local.

explained:

* alpaca-prod - the name of the service
* default - the namespace
* svc - this is a service
* cluster.local. - base domain name for the cluster

Readiness Checks

Modify for deployment:
Modify for deployment:
Modify for deployment:

[source,yaml]
----
spec:
  ...
  template:
    ...
    spec:
      containers:
        ...
        name: alpaca-prod
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          periodSeconds: 2
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1
----

----
$ kubectl get endpoints <service-name> --watch
----

Way to implement a graceful shutdown:
* signal that it no longer wants traffic
* wait until existing connections are closed
* then cleanly exit

ClusterIP - stable virtual IP that load-balance traffic
across all of the endpoints in a service.

This is performed by kube-proxy.

== HTTP Load Balancing with Ingress

Service object operates at Layer 4.

Ingress - HTTP-based load-balancing system (layer 7).

The ingress controller is a software system exposed
outside the cluster using a service of type _LoadBalancer_.

Sample ingress:

[source,yaml]
----
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: path-ingress
spec:
  rules:
  - host: bandicoot.example.com
    http:
      paths:
      - path: "/"
        backend:
          serviceName: bandicoot
          servicePort: 8080
      - path: "/a/"
        backend:
          serviceName: alpaca
          servicePort: 8080
----

=== TLS for ingress

Create secret
----
$ kubectl create secret tls <secret-name> --cert <certificate-pem-file> --key <private-key-pem-file>
----

or

[source,yaml]
----
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: tls-secret-name
type: kubernetes.io/tls
data:
  tls.crt: <base64 encoded certificate>
  tls.key: <base64 encoded private key>
----

tls-ingress.yaml

[source,yaml]
----
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tls-ingress
spec:
  tls:
  - hosts:
    - alpaca.example.com
    secretName: tls-secret-name
  rules:
  - host: alpaca.example.com
    http:
      paths:
      - backend:
          serviceName: alpaca
          servicePort: 8080
----

Available controllers:

* Contour (for Envoy proxy)
* nginx
* ambassador (Envoy-based)
* glo (Envoy-based)
* Traefik - implemented in Go

Service mesh products:

* Istio
* Linkerd

== ReplicaSets

Reasons for replication:

* redundancy - multiple running instances mean failure
  can be tolerated
* scale - more requests
* sharding - different replicas can handl edifferent part of
  a computation in parallel

Reconciliation loops - constantly running, observing the current
state and taking action to make the observed state
match the desired state.

== Deployments

----
$ kubectl scale deployment <deployment-name> --replicas=2
----

----
$ kubectl get deployment <depl-name> -o yaml > temp-deployment.yaml
$ kubectl replace -f temp-deployment.yaml --save-config
----

----
...
spec:
  ...
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "Update to green kuard"
...
----

----
$ kubectl rollout pause deployment <name>
$ kubectl rollout resume deployment <name>
$ kubectl rollout status deployment <name>
$ kubectl rollout history deployment <name>
$ kubectl rollout history deployment <name> --revision=2
$ kubectl rollout undo deployment <name>
$ kubectl rollout undo deployment <name> --to-revision=1
----

Deployment strategies:

* Recreate
* RollingUpdate

Rolling update parameters:

* maxUnavailable
* maxSurge - how many extra resources
* minReadySeconds - wait period after deploying a pod
* progressDeadlineSeconds - if any particular stage in the rollout
  fails to progress in specified time, then the deployment is
  marked as failed


== Daemon sets

