// suppress inspection "GrazieInspection" for whole file
// suppress inspection "PyInitNewSignature" for whole file
// suppress inspection "PyShadowingBuiltins" for whole file
// suppress inspection "PyUnusedLocal" for whole file
// suppress inspection "HtmlUnknownTarget" for whole file
// suppress inspection "PyStatementEffect" for whole file
// suppress inspection "PyShadowingNames" for whole file
// suppress inspection "PyArgumentList" for whole file
// suppress inspection "PyTypeChecker" for whole file
// suppress inspection "PyUnresolvedReferences" for whole file
= Python
:doc-root: https://notes.jdata.pl
:toc: left
:toclevels: 4
:tabsize: 4
:docinfo1:

== Basics

Python tutorial: https://docs.python.org/3/tutorial/

Zen of Python display after typing in python interpreter:

[source]
----
> import this
----

=== Compilation

[source,python]
python3 -m py_compile <file-name>


=== Exceptions

[source,python]
----
try:
    abc
except IndexError:
    println("error")
----

=== Encoding

 _# -*- coding: encoding -*-_

 _# -*- coding: cp-1252 -*-_

=== Types

* int
* float

python3 - division returns `float` (python2 - returns `int`)

to divide to int result use `//`

Remainder operator::
 8 % 3

powers::
 2 ** 8

In repl use _ to reference last result.

built-in support for complex numbers:

 >>> 5+10j

=== Strings

Single or double quotes, escaping with `\`

Raw strings::
 `r"C:\some\name"`

Repeating strings::
 `3 * 'um'`

There’s no separate char type - a character is a string of size one.

String operations:
|=====
|last character             |word[-1]
|substring                  |word[2:5]
|string without first char  |word[1:]
|string without last char   |word[:-1]
|length of string           |len(s)
|=====

Python strings cannot be changed.

Methods:

[options="header"]
|====
|Name           |Description

|title()        |Uppercases every word.
|upper()        |
|lower()        |
|rstrip()       |Trim right whitespaces
|lstrip()       |Trim left whitespaces
|strip()        |Trim whitespaces
|
|====

Concatenation with `+`

Whitespaces: `\t`, `\n`


== Variables

traceback - stacktrace for python

string methods:

* title()
* upper()
* lower()
* strip(), rstrip(), lstrip()

ints:

* exponent: `2 ** 3`

converting to string:

[source,python]
----
print("It's " + str(43))
----

Division:

* python3: 3 / 2 == 1.5
* python2: 3 / 2 == 1

== Lists

[source,python]
squares = [1, 4, 9, 16, 25]

|=====
|a copy of the list         |squares[:]
|concatenating lists        |squares + [36, 49]
|appending                  |squares.append(64)
|inserting                  |squares.insert(0, 1)
|delete single element      |del squares[0]
|delete and return element  |squares.pop(0)
|remove item by value       |squares.remove(4)
|replace slice              |squares[2:5] = [3, 4]
|remove slice               |squares[2:5] = []
|reset list                 |squares[:] = []
|list length                |len(squares)
|sorting                    |squares.sort()
|=====

Evaluating predicates:

* true is:
** any non-zero number
** non-zero length string or list

When printing use end= to override new line:

[source,python]
print(i, end=’,’)

[source,python]
----
names = ['Jack', 'Jim', 'Johnny']

for name in names:
    print(name)
----

=== Sorting

[source,python]
----
list.sort()
list.sort(reverse=True)
----

To maintain original list:

[source,python]
----
sorted(list)
----

=== Reversing

[source,python]
----
list.reverse()
----

Ranges

[source,python]
----
for value in range(1, 5):
    print(value)
----

List of numbers:

[source,python]
----
numbers = list(range(1, 6))
print(numbers)
----

[source,python]
----
squares = []

for x in range(1, 11):
    squares.append(x ** 2)

print(squares)
----

Aggregation functions:

[source,python]
----
digits = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0]

print('min: %d' % min(digits))
print('max: %d' % max(digits))
print('sum: %d' % sum(digits))
----

List comprehensions:

[source,python]
----
squares = [value ** 2 for value in range(1, 11)]
print(squares)
----

=== Tuples

[source,python]
----
dimensions = (200, 50)
print(dimensions[0])
print(dimensions[1])
----

== if statement

[source,python]
----
cars = ['audi', 'bmw', 'subaru', 'toyota']

for car in cars:
    if car == 'bmw':
        print(car.upper())
    else:
        print(car.title())
----

Logical operators: `and`, `or`

Checking if value is in the list:

[source,python]
----
toppings = ['onions', 'mushrooms', 'pineapple']

if 'mushrooms' in toppings:
    print('Hurray!!!')
----

Checking if value is not in the list:

[source,python]
----
if user not in banned_users:
       print(user.title() + ", you can post a response if you wish.")
----

elif statement:

[source,python]
----
age = 12

if age < 4:
    print("Your admission cost is $0.")
elif age < 18:
    print("Your admission cost is $5.")
else:
    print("Your admission cost is $10.")
----

Checking if list is empty:

[source,python]
----
requested_toppings = []

if not requested_toppings:
    print("Requested toppings is empty")
requested_toppings = []
----

== Dictionaries

[source,python]
----
alien = {'color': 'green', 'points': 5}

print(alien['color'])
print(alien['points'])
----

Defining new key in a dictionary:

[source,python]
----
alien['x-position'] = 250
----

Removing key-value

[source,python]
----
del alien['points']
----

Looping through dictionary

[source,python]
----
alien = {'color': 'green', 'points': 5}

for key, value in alien.items():
    print(str(key) + " : " + str(value))
----

Looping through keys:

[source,python]
----
favorite_languages = {'pl': 'polish', 'en': 'english', 'sp': 'spanish'}

for key in favorite_languages.keys():
    print(key, "-", favorite_languages[key])

for key, value in favorite_languages.items():
    print(key, "-", value)
----

Dictionary methods:

* items()
* keys()
* values()

Set construction:

[source,python]
----
set(favorite_languages.values())
----

Dictionary throws `KeyError` when trying to reference non-existent key.

Default value:

[source,python]
----
picnic_items.get('eggs', 0)
----

Setting value if key does not exist:

[source,python]
----
picnic_items.setdefault('wine', 1)
----

Pretty printing:

[source,python]
----
pprint.pprint(picnic_items)

str = pprint.pformat(picnic_items)
----

== User input

[source,python]
----
message = input("Tell me something, and I will repeat it back to you: ")
print(message)
----

== while loop

[source,python]
----
current_number = 1

while current_number <= 5:
    print(current_number)
    current_number += 1
----

break statement:

[source,python]
----
while True:
    city = input(prompt)

    if city == 'quit':
        break
    else:
        print("I'd love to go to " + city.title() + "!")
----

You can also use `continue` statement.

Removing all instances of specific value from a list:

[source,python]
----
pets = ['dog', 'cat', 'dog', 'goldfish', 'cat', 'rabbit', 'cat']
print(pets)

while 'cat' in pets:
    pets.remove('cat')

print(pets)
----

== Functions

[source,python]
----
def fib(n):
    """Print a Fibonacci series up to n."""
    a, b = 0, 1
    while a < n:
        print(a, end=' ')
        a, b = b, a + b
    print()
fib(2000)
----

The first statement in the body of the function can optionally
be a string literal - this string literal is the function’s
documentation string, or _docstring_.

Functions without return statement return None value.

[source,python]
----
def greet_user(username):
    """Display a simple greeting."""
    print("Hello, " + username.title() + "!")

greet_user('jesse')
----

docstrings are enclosed in triple quotes.

=== Keyword arguments

[source,python]
----
describe_pet(animal_type='dog', pet_name='willie')
----

=== Default values

[source,python]
----
def describe_pet(pet_name, animal_type='dog'):
    print("My " + animal_type + "'s name is " + pet_name.title() + ".")

describe_pet('harry')
----

=== Global statement

When you need to modify a global variable from within a function.

[source,python]
----
state = 'Idle'

def sample():
    global state
    state = 'Running'

sample()
print(state)
----

=== Returning value and arbitrary number of arguments.

[source,python]
----
def avg(*args):
    return sum(args) / len(args)

print(avg(1, 2, 3))
----

`args` argument is a tuple.

==== Using arbitrary keyword arguments

[source,python]
----
def build_profile(first, last, **user_info):
    profile = {
        'first_name': first.title(),
        'last_name': last.title()
    }

    for key, value in user_info.items():
        profile[key] = value

    return profile


profile = build_profile('albert', 'einstein',
                        location='princeton',
                        field='physics')
----

=== Modules

First file: `pizza.py`

[source,python]
----
def make_pizza(size, *toppings):
    """Summarize the pizza we are about to make."""
    print("\nMaking a " + str(size) +
          "-inch pizza with the following toppings:")
    for topping in toppings:
        print("- " + topping)
----

Second file:

[source,python]
----
import pizza

pizza.make_pizza(16, 'pepperoni')
pizza.make_pizza(12, 'mushrooms', 'green peppers', 'extra cheese')
----

Imported functions are available in a format:

----
__module_name.function_name__()
----

Importing specific functions:

----
from _module_name_ import _function_name_
----

----
from _module_name_ import _function_name_1_, _function_name_2_
----

Giving an alias to a function

[source,python]
----
from pizza import make_pizza as mp

mp(16, 'pepperoni')
----

Give an alias to a module

[source,python]
----
import pizza as p

p.make_pizza(16, 'pepperoni')
----

Importing all functions

[source,python]
----
from pizza import *

make_pizza(16, 'pepperoni')
----

== Classes

[source,python]
----
class Dog:
    """A simple attempt to model a dog."""


    def __init__(self, name, age):
        """Initialize named and age attributes"""
        self.name = name
        self.age = age


    def sit(self):
        """Simulate a dog sitting in response to a command."""
        print(self.name.title() + " is now sitting.")


    def roll_over(self):
        """Simulate rolling over in response to a command."""
        print(self.name.title() + " rolled over!")


my_dog = Dog('willie', 6)

my_dog.sit()
my_dog.roll_over()
----

Creating classes in python 2:

[source,python]
----
class Dog(object):
    nop # --snip--
----

=== Inheritance

[source,python]
----
class Car:
    def __init__(self, param1):
        nop # --snip--


class ElectricCar(Car):
    def __init__(self, param1):
        super().__init__(param1)
----

In python2:

[source,python]
----
class ElectricCar(Car):
    def __init__(self, param1):
        super(ElectricCar, self).__init__(param1)
----

=== Python stdlib

[source,python]
----
from collections import OrderedDict
----

== Files

Opening a file

[source,python]
----
with open('pi_digits.txt') as file_object:
    contents = file_object.read()
    print(contents)
----

Reading a file line by line:

[source,python]
----
with open('text_files/pi_digits.txt') as file_object:
    for line in file_object:
        print(line.rstrip())
----

file object methods:

* read()
* readlines()

=== Writing to a file

[source,python]
----
filename = 'programming.txt'

with open(filename, "w") as file_object:
    file_object.write("I love programming.")
----

File opening modes:

* w - replaces file contents
* r+ - read-write
* a - append
* r - read (default)

=== Storing data as json

[source,python]
----
import json

filename = 'numbers.json'
numbers = [1, 2, 3]

with open(filename, "w") as file_object:
    json.dump(numbers, file_object)
----

[source,python]
----
import json

filename = "numbers.json"

with open(filename, "r") as file_object:
    print(json.load(file_object))
----

== Exceptions

[source,python]
----
try:
    print(5 / 0)
except ZeroDivisionError:
    print('You can\'t divide by zero')
else:
    print('Success')
----

Failing silently

[source,python]
----
try:
    print(5 / 0)
except ZeroDivisionError:
    pass
else:
    print('Success')
----

== Unit tests

[source,python]
----
import unittest
from name_function import get_formatted_name

class NamesTestCase(unittest.TestCase):
    """Tests for 'name_function.py'."""

    def test_first_last_name(self):
        """Do names like 'Janis Joplin' work?"""
        formatted_name = get_formatted_name('janis', 'joplin')
        self.assertEqual(formatted_name, 'Janis Joplin')

unittest.main()
----

The method name must start with `test_`

Assert methods:

* assertEqual(a, b)
* assertNotEqual(a, b)
* assertTrue(x)
* assertFalse(x)
* assertIn(item, list)
* assertNotIn(item, list)


== Packages and virtual environments

Location of third party packages:

[source,python]
----
import site
site.getsitepackages()
----

virtual environments - to create an isolated environment
on Python projects.

Installing on ubuntu:

----
$ sudo apt install python3-venv
----

Updating package tools:

----
$ python -m pip install --upgrade pip setuptools wheel
----

Creating virtual envinorment:

----
$ python3 -m venv /path/to/my/env
----

Created directory structure:

* bin - files that interact with virtual environment
    ** activate
    ** pip
    ** python
* include - C headers that compile the Python packages
* lib - a copy of the Python version along with a site-packages
    folder where each dependency is installed
    ** python3.5
        *** site-packages
* pyvenv.cfg

Activate virtual env:

----
$ . env/bin/activate
----

Deactivating:

----
$ deactivate
----

When python is starting up, it looks at the path of its binary.

It then sets the location of `sys.prefix` and `sys.exec_prefix`
based on this location.

`sys.prefix` - used for locating the site-packages directory

`sys.path` - array which contains all of the locations where
package can reside.

virtualenvwrapper::
    * organizes virtual environments in one location
    * provides methods to help you easily create, delete
      and copy environments
    * single command to switch between environments

Installing virtualenvwrapper:

----
$ pip install virtualenvwrapper
$ which virtualenvwrapper.sh
----

=== Main function

[source,python]
----
if __name__ == '__main__':
    my_main_func()
----

=== Custom import name

[source,python]
----
if visual_mode:
    import draw_visual as draw
else:
    import draw_textual as draw

draw.draw_game()
----

=== Extending module load path

 $ PYTHONPATH=/foo python3 game.py

=== Exploring built-in modules

[source,python]
----
import urllib

for module in dir(urllib):
    print(module)

help(urllib.urlopen)
----

== Method decorators

Normal decorator:

[source,python]
----
def get_text(name):
    return "lorem ipsum, {0} dolor sit amet".format(name)

def p_decorate(func):
    def func_wrapper(name):
        return "<p>{0}</p>".format(func(name))
    return func_wrapper

my_get_text = p_decorate(get_text)

print(my_get_text("Michael"))
----

With python decorator:

[source,python]
----
def p_decorate(func):
    def func_wrapper(name):
        return "<p>{0}</p>".format(func(name))
    return func_wrapper

@p_decorate
def get_text(name):
    return "lorem ipsum, {0} dolor sit amet".format(name)

print(get_text("Michael"))
----

Method decorator:

[source,python]
----
def p_decorate(func):
    def func_wrapper(self):
        return "<p>{0}</p>".format(func(self))
    return func_wrapper

class Person:
    def __init__(self):
        self.name = "John"
        self.family = "Doe"

    @p_decorate
    def get_fullname(self):
        return self.name + " " + self.family

my_person = Person()

print(my_person.get_fullname())
----

== pip

Checking if pip is installed

----
$ python -m pip --version
----

Installing pip

----
$ python get-pip.py
----

== Flask

Main dependencies:

* Werkzeug - routing, debugging, Web Server Gateway Interface (WSGI)
* Jinja2 - templates
* Click - command-line integration

Create virtual env:

----
$ python3 -m venv venv
$ . venv/bin/activate
$ pip install flask
$ pip freeze
----

Simplest route:

[source,python]
----
@app.route("/")
def index():
    return "<h1>Hello World!</h1>"
----

Route params:

[source,python]
----
@app.route("/user/<name>")
def user(name):
    return "<h1>Hello, {}!</h1>".format(name)
----

Example parameterized route with type:

`/user/<int:id>`

Flask supports params of type: string, int, float and path.

To run Flask dev server:

----
$ export FLASK_APP=first.py
$ flask run
----

Enabling debug mode:

----
$ export FLASK_DEBUG=1
----

Listening on all interfaces:

----
$ flask run --host 0.0.0.0
----

Getting request attributes:

[source,python]
----
from flask import request

@app.route("/")
def index():
    user_agent = request.headers.get('User-Agent')
----

=== Contexts

There are two contexts in Flask:

* application context
* request context

Context global variables:

* current_app
* g - temporary storage during request handling. Reset with each
  request
* request
* session

Request object attributes and methods:

* form - a dictionary with all the form fields
* args - query string dictionary
* values - dictionary - args and form
* cookies - dictionary
* headers - dictionary
* files - dictionary
* get_data() - buffered request body
* get_json() - parsed json body
* blueprint - Flask blueprint handling the request
* endpoint - Flask endpoint handling the request
* method - HTTP method
* scheme - http or https
* is_secure() - True if https connection
* host - host defined in the request
* path - the path portion of the url
* query_string
* full_path
* url - complete url
* base_url - url without query string
* remote_addr - ip addr of the client
* environ - raw WSGI environment dictionary for the request

=== Request hooks

* before_request
* before_first_request
* after_request - run only when no unhandled exceptions
* teardown_request - run always

=== Responses

Returning status code:

[source,python]
----
@app.route("/bad")
def bad():
    return "<h1>Bad request</h1>", 400
----

Response object:

* status_code - numeric
* headers - dictionary-like object
* set_cookie()
* delete_cookie()
* content_length
* content_type
* set_data() - response body
* get_data() - response body

Redirecting:

[source,python]
----
from flask import redirect

@app.route("/red")
def red():
    return redirect("/user")
----

Aborting:

[source,python]
----
from flask import abort

@app.route('/user/<id>')
def get_user(id):
    user = load_user(id)
    if not user:
        abort(404)
    return '<h1>Hello, {}</h1>'.format(user.name)
----

=== Templates

[source,python]
----
from flask import render_template

@app.route("/user/<name>")
def user(name):
    return render_template("user.html", name=name)
----

Filters:

----
Hello, {{ name|capitalize }}!
----

* safe - renders the value without applying escaping
* capitalize
* lower
* upper
* title
* striptags

==== Control structures

If:

----
{% if user %}
    Hello, {{ user }}!
{% else %}
    Hello, Stranger!
{% endif %}
----

Loop:

----
<ul>
    {% for comment in comments %}
        <li>{{ comment }}</li>
    {% endfor %}
</ul>
----

Macros:

----
{% macro render_comment(comment) %}
    <li>{{ comment }}</li>
{% endmacro %}

<ul>
    {% for comment in comments %}
        {{ render_comment(comment) }}
    {% endfor %}
</ul>
----

Importing macros:

----
{% import 'macros.html' as macros %}
<ul>
    {% for comment in comments %}
        {{ macros.render_comment(comment) }}
    {% endfor %}
</ul>
----

Including other file:

----
{% include 'common.html' %}
----

===== Blocks

"base.html" file:

----
<html>
<head>
    {% block head %}
    <title>{% block title %}{% endblock %} - My Application</title>
    {% endblock %}
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>
----

Extending template:

----
{% extends "base.html" %}
{% block title %}Index{% endblock %}
{% block head %}
    {{ super() }}
    <style>
    </style>
{% endblock %}
{% block body %}
<h1>Hello, World!</h1>
{% endblock %}
----

=== Bootstrap integration

----
$ pip install flask-bootstrap
----

[source,python]
----
from flask_bootstrap import Bootstrap

app = Flask(__name__)
bootstrap = Bootstrap(app)
----

Sample bootstrap-basing template:

[source,html]
----
{% extends "bootstrap/base.html" %}

{% block title %}Flasky{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle"
             data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Flasky</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="page-header">
        <h1>Hello, {{ name }}!</h1>
    </div>
</div>
{% endblock %}
----

Flask-Bootstrap's base template blocks:

* doc - entire document
* html_attribs - attributes inside <html> tag
* html - the contents of the <html> tag
* head - the contents of the <head> tag
* title - the contents of the <title> tag
* metas - the list of <meta> tags
* styles - css definitions
* body_attribs - <body> attributes
* body - contents of <body> tag
* navbar - user defined navigation bar
* content - user-defined page content
* scripts - JavaScript declarations at the bottom
  of the document.

Custom error page

[source,python]
----
@app.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

@app.errorhandler(500)
def internal_server_error(e):
    return render_template('500.html'), 500
----

=== Generating urls

[source,python]
----
url_for('user', name='john', _external=True)
----

`_external=True` generates full url.

Favicon definition:

----
{% block head %}
{{ super() }}
<link rel="shortcut icon"
    href="{{ url_for('static', filename='favicon.ico') }}"
    type="image/x-icon">
<link rel="icon"
    href="{{ url_for('static', filename='favicon.ico') }}"
    type="image/x-icon">
{% endblock %}
----

=== moment.js

Moment.js is JavaScript library that renders dates and times
in the browser.

Installing flask-moment:

----
$ pip install flask-moment
----

Including moment.js in base template:

[source,jinja2]
----
{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}
----

Working with timestamps:

[source,python]
----
from datetime import datetime
from flask_moment import Moment

moment = Moment(app)
@app.route('/')
def hello_world():
    return render_template('index.html',
                           current_time=datetime.now())
----

Template:

[source,html]
----
<p>The local date and time is {{  moment(current_time).format('LLL') }}.</p>
<p>That was {{ moment(current_time).fromNow(refresh=True) }}</p>
<a href="{{ url_for('user', name='jacek') }}">User</a>
----

=== WTForms

Installing:

----
$ pip install flask-wtf
----

